<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * Statements in braces.
 */
final class BlockNode extends StatementNode
{
	/**
	 * @param NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openBrace,
		public NodeList $stmts,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openBrace, $this->stmts, $this->closeBrace];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param NodeList<StatementNode> $stmts */
	public function setStmts(NodeList $stmts): void
	{
		$this->adopt($stmts);
		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
