<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * break with an optional level.
 */
final class BreakNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $breakKeyword,
		public ?ExpressionNode $expr,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->breakKeyword;
		if ($this->expr) {
			$children[] = $this->expr;
		}
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->breakKeyword) {
			$this->setBreakKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('breakKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setBreakKeyword(Token $breakKeyword): void
	{
		$this->adopt($breakKeyword);
		$this->release($this->breakKeyword);
		$this->breakKeyword = $breakKeyword;
		$this->structureChanged();
	}


	public function setExpr(?ExpressionNode $expr): void
	{
		if ($expr) {
			$this->adopt($expr);
		}

		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
