<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ConstItemNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * const statement outside a class.
 */
final class ConstNode extends StatementNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param SeparatedNodeList<ConstItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public Token $constKeyword,
		public SeparatedNodeList $items,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->attributes, $this->constKeyword, $this->items, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->constKeyword) {
			$this->setConstKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('constKeyword', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<ConstItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setConstKeyword(Token $constKeyword): void
	{
		$this->adopt($constKeyword);
		$this->release($this->constKeyword);
		$this->constKeyword = $constKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ConstItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
