<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * do-while loop.
 */
final class DoWhileNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $doKeyword,
		public StatementNode $body,
		public Token $whileKeyword,
		public Token $openParen,
		public ExpressionNode $cond,
		public Token $closeParen,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->doKeyword, $this->body, $this->whileKeyword, $this->openParen, $this->cond, $this->closeParen, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->doKeyword) {
			$this->setDoKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('doKeyword', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof StatementNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->whileKeyword) {
			$this->setWhileKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('whileKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setDoKeyword(Token $doKeyword): void
	{
		$this->adopt($doKeyword);
		$this->release($this->doKeyword);
		$this->doKeyword = $doKeyword;
		$this->structureChanged();
	}


	public function setBody(StatementNode $body): void
	{
		$this->adopt($body);
		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setWhileKeyword(Token $whileKeyword): void
	{
		$this->adopt($whileKeyword);
		$this->release($this->whileKeyword);
		$this->whileKeyword = $whileKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setCond(ExpressionNode $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
