<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * echo statement; the keyword may be the <?= open tag and the semicolon a close tag.
 */
final class EchoNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<ExpressionNode> $exprs
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $echoKeyword,
		public SeparatedNodeList $exprs,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->echoKeyword, $this->exprs, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->echoKeyword) {
			$this->setEchoKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('echoKeyword', $new));
		} elseif ($old === $this->exprs) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('exprs', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setExprs($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setEchoKeyword(Token $echoKeyword): void
	{
		$this->adopt($echoKeyword);
		$this->release($this->echoKeyword);
		$this->echoKeyword = $echoKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $exprs */
	public function setExprs(SeparatedNodeList $exprs): void
	{
		$this->adopt($exprs);
		$this->release($this->exprs);
		$this->exprs = $exprs;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
