<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * Bare semicolon, or a close tag after a terminated statement.
 */
final class EmptyStatementNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
