<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ClassLikeNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Enum declaration, optionally backed by a scalar type.
 */
final class EnumNode extends StatementNode implements ClassLikeNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param ?SeparatedNodeList<NameNode> $implements
	 * @param NodeList<MemberNode> $members
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public Token $enumKeyword,
		public IdentifierNode $name,
		public ?Token $colon,
		public ?TypeNode $scalarType,
		public ?Token $implementsKeyword,
		public ?SeparatedNodeList $implements,
		public Token $openBrace,
		public NodeList $members,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->enumKeyword;
		$children[] = $this->name;
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->scalarType) {
			$children[] = $this->scalarType;
		}
		if ($this->implementsKeyword) {
			$children[] = $this->implementsKeyword;
		}
		if ($this->implements) {
			$children[] = $this->implements;
		}
		$children[] = $this->openBrace;
		$children[] = $this->members;
		$children[] = $this->closeBrace;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->enumKeyword) {
			$this->setEnumKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('enumKeyword', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->scalarType) {
			$this->setScalarType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('scalarType', $new));
		} elseif ($old === $this->implementsKeyword) {
			$this->setImplementsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('implementsKeyword', $new));
		} elseif ($old === $this->implements) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('implements', $new);
			}

			/** @var SeparatedNodeList<NameNode> $new  the item type is erased at runtime */
			$this->setImplements($new);
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->members) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('members', $new);
			}

			/** @var NodeList<MemberNode> $new  the item type is erased at runtime */
			$this->setMembers($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setEnumKeyword(Token $enumKeyword): void
	{
		$this->adopt($enumKeyword);
		$this->release($this->enumKeyword);
		$this->enumKeyword = $enumKeyword;
		$this->structureChanged();
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setScalarType(?TypeNode $scalarType): void
	{
		if ($scalarType) {
			$this->adopt($scalarType);
		}

		$this->release($this->scalarType);
		$this->scalarType = $scalarType;
		$this->structureChanged();
	}


	public function setImplementsKeyword(?Token $implementsKeyword): void
	{
		if ($implementsKeyword) {
			$this->adopt($implementsKeyword);
		}

		$this->release($this->implementsKeyword);
		$this->implementsKeyword = $implementsKeyword;
		$this->structureChanged();
	}


	/** @param ?SeparatedNodeList<NameNode> $implements */
	public function setImplements(?SeparatedNodeList $implements): void
	{
		if ($implements) {
			$this->adopt($implements);
		}

		$this->release($this->implements);
		$this->implements = $implements;
		$this->structureChanged();
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param NodeList<MemberNode> $members */
	public function setMembers(NodeList $members): void
	{
		$this->adopt($members);
		$this->release($this->members);
		$this->members = $members;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
