<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * foreach loop in either syntax; the value may be a variable, a list or an array pattern.
 */
final class ForeachNode extends StatementNode
{
	/**
	 * @param ?NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $foreachKeyword,
		public Token $openParen,
		public ExpressionNode $expr,
		public Token $asKeyword,
		public ?ExpressionNode $keyVar,
		public ?Token $doubleArrow,
		public ?Token $byRef,
		public ExpressionNode $valueVar,
		public Token $closeParen,
		public ?StatementNode $body,
		public ?Token $colon,
		public ?NodeList $stmts,
		public ?Token $endKeyword,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->foreachKeyword;
		$children[] = $this->openParen;
		$children[] = $this->expr;
		$children[] = $this->asKeyword;
		if ($this->keyVar) {
			$children[] = $this->keyVar;
		}
		if ($this->doubleArrow) {
			$children[] = $this->doubleArrow;
		}
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		$children[] = $this->valueVar;
		$children[] = $this->closeParen;
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->stmts) {
			$children[] = $this->stmts;
		}
		if ($this->endKeyword) {
			$children[] = $this->endKeyword;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->foreachKeyword) {
			$this->setForeachKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('foreachKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} elseif ($old === $this->asKeyword) {
			$this->setAsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('asKeyword', $new));
		} elseif ($old === $this->keyVar) {
			$this->setKeyVar($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('keyVar', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->valueVar) {
			$this->setValueVar($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('valueVar', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof StatementNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} elseif ($old === $this->endKeyword) {
			$this->setEndKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('endKeyword', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setForeachKeyword(Token $foreachKeyword): void
	{
		$this->adopt($foreachKeyword);
		$this->release($this->foreachKeyword);
		$this->foreachKeyword = $foreachKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}


	public function setAsKeyword(Token $asKeyword): void
	{
		$this->adopt($asKeyword);
		$this->release($this->asKeyword);
		$this->asKeyword = $asKeyword;
		$this->structureChanged();
	}


	public function setKeyVar(?ExpressionNode $keyVar): void
	{
		if ($keyVar) {
			$this->adopt($keyVar);
		}

		$this->release($this->keyVar);
		$this->keyVar = $keyVar;
		$this->structureChanged();
	}


	public function setDoubleArrow(?Token $doubleArrow): void
	{
		if ($doubleArrow) {
			$this->adopt($doubleArrow);
		}

		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setValueVar(ExpressionNode $valueVar): void
	{
		$this->adopt($valueVar);
		$this->release($this->valueVar);
		$this->valueVar = $valueVar;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setBody(?StatementNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	/** @param ?NodeList<StatementNode> $stmts */
	public function setStmts(?NodeList $stmts): void
	{
		if ($stmts) {
			$this->adopt($stmts);
		}

		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}


	public function setEndKeyword(?Token $endKeyword): void
	{
		if ($endKeyword) {
			$this->adopt($endKeyword);
		}

		$this->release($this->endKeyword);
		$this->endKeyword = $endKeyword;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
