<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * for loop in either syntax.
 */
final class ForNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<ExpressionNode> $init
	 * @param SeparatedNodeList<ExpressionNode> $cond
	 * @param SeparatedNodeList<ExpressionNode> $loop
	 * @param ?NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $forKeyword,
		public Token $openParen,
		public SeparatedNodeList $init,
		public Token $initSemicolon,
		public SeparatedNodeList $cond,
		public Token $condSemicolon,
		public SeparatedNodeList $loop,
		public Token $closeParen,
		public ?StatementNode $body,
		public ?Token $colon,
		public ?NodeList $stmts,
		public ?Token $endKeyword,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->forKeyword;
		$children[] = $this->openParen;
		$children[] = $this->init;
		$children[] = $this->initSemicolon;
		$children[] = $this->cond;
		$children[] = $this->condSemicolon;
		$children[] = $this->loop;
		$children[] = $this->closeParen;
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->stmts) {
			$children[] = $this->stmts;
		}
		if ($this->endKeyword) {
			$children[] = $this->endKeyword;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->forKeyword) {
			$this->setForKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('forKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->init) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('init', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setInit($new);
		} elseif ($old === $this->initSemicolon) {
			$this->setInitSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('initSemicolon', $new));
		} elseif ($old === $this->cond) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('cond', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setCond($new);
		} elseif ($old === $this->condSemicolon) {
			$this->setCondSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('condSemicolon', $new));
		} elseif ($old === $this->loop) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('loop', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setLoop($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof StatementNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} elseif ($old === $this->endKeyword) {
			$this->setEndKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('endKeyword', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setForKeyword(Token $forKeyword): void
	{
		$this->adopt($forKeyword);
		$this->release($this->forKeyword);
		$this->forKeyword = $forKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $init */
	public function setInit(SeparatedNodeList $init): void
	{
		$this->adopt($init);
		$this->release($this->init);
		$this->init = $init;
		$this->structureChanged();
	}


	public function setInitSemicolon(Token $initSemicolon): void
	{
		$this->adopt($initSemicolon);
		$this->release($this->initSemicolon);
		$this->initSemicolon = $initSemicolon;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $cond */
	public function setCond(SeparatedNodeList $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setCondSemicolon(Token $condSemicolon): void
	{
		$this->adopt($condSemicolon);
		$this->release($this->condSemicolon);
		$this->condSemicolon = $condSemicolon;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $loop */
	public function setLoop(SeparatedNodeList $loop): void
	{
		$this->adopt($loop);
		$this->release($this->loop);
		$this->loop = $loop;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setBody(?StatementNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	/** @param ?NodeList<StatementNode> $stmts */
	public function setStmts(?NodeList $stmts): void
	{
		if ($stmts) {
			$this->adopt($stmts);
		}

		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}


	public function setEndKeyword(?Token $endKeyword): void
	{
		if ($endKeyword) {
			$this->adopt($endKeyword);
		}

		$this->release($this->endKeyword);
		$this->endKeyword = $endKeyword;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
