<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * global statement.
 */
final class GlobalNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<ExpressionNode> $vars
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $globalKeyword,
		public SeparatedNodeList $vars,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->globalKeyword, $this->vars, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->globalKeyword) {
			$this->setGlobalKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('globalKeyword', $new));
		} elseif ($old === $this->vars) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('vars', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setVars($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setGlobalKeyword(Token $globalKeyword): void
	{
		$this->adopt($globalKeyword);
		$this->release($this->globalKeyword);
		$this->globalKeyword = $globalKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $vars */
	public function setVars(SeparatedNodeList $vars): void
	{
		$this->adopt($vars);
		$this->release($this->vars);
		$this->vars = $vars;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
