<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * goto statement.
 */
final class GotoNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $gotoKeyword,
		public IdentifierNode $label,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->gotoKeyword, $this->label, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->gotoKeyword) {
			$this->setGotoKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('gotoKeyword', $new));
		} elseif ($old === $this->label) {
			$this->setLabel($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('label', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setGotoKeyword(Token $gotoKeyword): void
	{
		$this->adopt($gotoKeyword);
		$this->release($this->gotoKeyword);
		$this->gotoKeyword = $gotoKeyword;
		$this->structureChanged();
	}


	public function setLabel(IdentifierNode $label): void
	{
		$this->adopt($label);
		$this->release($this->label);
		$this->label = $label;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
