<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Nodes\UseItemNode;
use PhpSyntax\Token;


/**
 * Group use import: use A\{B, C};.
 */
final class GroupUseNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<UseItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $useKeyword,
		public ?Token $type,
		public NameNode $prefix,
		public Token $namespaceSeparator,
		public Token $openBrace,
		public SeparatedNodeList $items,
		public Token $closeBrace,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->useKeyword;
		if ($this->type) {
			$children[] = $this->type;
		}
		$children[] = $this->prefix;
		$children[] = $this->namespaceSeparator;
		$children[] = $this->openBrace;
		$children[] = $this->items;
		$children[] = $this->closeBrace;
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->useKeyword) {
			$this->setUseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('useKeyword', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof Token ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->prefix) {
			$this->setPrefix($new instanceof NameNode ? $new : throw self::describeSlotMismatch('prefix', $new));
		} elseif ($old === $this->namespaceSeparator) {
			$this->setNamespaceSeparator($new instanceof Token ? $new : throw self::describeSlotMismatch('namespaceSeparator', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<UseItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setUseKeyword(Token $useKeyword): void
	{
		$this->adopt($useKeyword);
		$this->release($this->useKeyword);
		$this->useKeyword = $useKeyword;
		$this->structureChanged();
	}


	public function setType(?Token $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	public function setPrefix(NameNode $prefix): void
	{
		$this->adopt($prefix);
		$this->release($this->prefix);
		$this->prefix = $prefix;
		$this->structureChanged();
	}


	public function setNamespaceSeparator(Token $namespaceSeparator): void
	{
		$this->adopt($namespaceSeparator);
		$this->release($this->namespaceSeparator);
		$this->namespaceSeparator = $namespaceSeparator;
		$this->structureChanged();
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<UseItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
