<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * __halt_compiler(); the rest of the file is the data token.
 */
final class HaltCompilerNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $haltKeyword,
		public Token $openParen,
		public Token $closeParen,
		public Token $semicolon,
		public ?Token $data,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->haltKeyword;
		$children[] = $this->openParen;
		$children[] = $this->closeParen;
		$children[] = $this->semicolon;
		if ($this->data) {
			$children[] = $this->data;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->haltKeyword) {
			$this->setHaltKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('haltKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} elseif ($old === $this->data) {
			$this->setData($new instanceof Token ? $new : throw self::describeSlotMismatch('data', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setHaltKeyword(Token $haltKeyword): void
	{
		$this->adopt($haltKeyword);
		$this->release($this->haltKeyword);
		$this->haltKeyword = $haltKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}


	public function setData(?Token $data): void
	{
		if ($data) {
			$this->adopt($data);
		}

		$this->release($this->data);
		$this->data = $data;
		$this->structureChanged();
	}
}
