<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ElseIfNode;
use PhpSyntax\Nodes\ElseNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * if statement in either syntax; the body is a statement, the alternative syntax fills stmts.
 */
final class IfNode extends StatementNode
{
	/**
	 * @param ?NodeList<StatementNode> $stmts
	 * @param NodeList<ElseIfNode> $elseifs
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $ifKeyword,
		public Token $openParen,
		public ExpressionNode $cond,
		public Token $closeParen,
		public ?StatementNode $body,
		public ?Token $colon,
		public ?NodeList $stmts,
		public NodeList $elseifs,
		public ?ElseNode $else,
		public ?Token $endKeyword,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->ifKeyword;
		$children[] = $this->openParen;
		$children[] = $this->cond;
		$children[] = $this->closeParen;
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->stmts) {
			$children[] = $this->stmts;
		}
		$children[] = $this->elseifs;
		if ($this->else) {
			$children[] = $this->else;
		}
		if ($this->endKeyword) {
			$children[] = $this->endKeyword;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->ifKeyword) {
			$this->setIfKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('ifKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof StatementNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} elseif ($old === $this->elseifs) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('elseifs', $new);
			}

			/** @var NodeList<ElseIfNode> $new  the item type is erased at runtime */
			$this->setElseifs($new);
		} elseif ($old === $this->else) {
			$this->setElse($new instanceof ElseNode ? $new : throw self::describeSlotMismatch('else', $new));
		} elseif ($old === $this->endKeyword) {
			$this->setEndKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('endKeyword', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setIfKeyword(Token $ifKeyword): void
	{
		$this->adopt($ifKeyword);
		$this->release($this->ifKeyword);
		$this->ifKeyword = $ifKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setCond(ExpressionNode $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setBody(?StatementNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	/** @param ?NodeList<StatementNode> $stmts */
	public function setStmts(?NodeList $stmts): void
	{
		if ($stmts) {
			$this->adopt($stmts);
		}

		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}


	/** @param NodeList<ElseIfNode> $elseifs */
	public function setElseifs(NodeList $elseifs): void
	{
		$this->adopt($elseifs);
		$this->release($this->elseifs);
		$this->elseifs = $elseifs;
		$this->structureChanged();
	}


	public function setElse(?ElseNode $else): void
	{
		if ($else) {
			$this->adopt($else);
		}

		$this->release($this->else);
		$this->else = $else;
		$this->structureChanged();
	}


	public function setEndKeyword(?Token $endKeyword): void
	{
		if ($endKeyword) {
			$this->adopt($endKeyword);
		}

		$this->release($this->endKeyword);
		$this->endKeyword = $endKeyword;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
