<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * Text outside PHP tags, including a BOM or a hashbang line.
 */
final class InlineHtmlNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $html,
	) {
	}


	public function getChildren(): array
	{
		return [$this->html];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->html) {
			$this->setHtml($new instanceof Token ? $new : throw self::describeSlotMismatch('html', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setHtml(Token $html): void
	{
		$this->adopt($html);
		$this->release($this->html);
		$this->html = $html;
		$this->structureChanged();
	}
}
