<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * Label for goto.
 */
final class LabelNode extends StatementNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public IdentifierNode $name,
		public Token $colon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->name, $this->colon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setColon(Token $colon): void
	{
		$this->adopt($colon);
		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}
}
