<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * namespace declaration; after "namespace A;" the following statements are nested in it.
 */
final class NamespaceNode extends StatementNode
{
	/**
	 * @param NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $namespaceKeyword,
		public ?NameNode $name,
		public ?Token $semicolon,
		public ?Token $openBrace,
		public NodeList $stmts,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->namespaceKeyword;
		if ($this->name) {
			$children[] = $this->name;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		$children[] = $this->stmts;
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->namespaceKeyword) {
			$this->setNamespaceKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('namespaceKeyword', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof NameNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setNamespaceKeyword(Token $namespaceKeyword): void
	{
		$this->adopt($namespaceKeyword);
		$this->release($this->namespaceKeyword);
		$this->namespaceKeyword = $namespaceKeyword;
		$this->structureChanged();
	}


	public function setName(?NameNode $name): void
	{
		if ($name) {
			$this->adopt($name);
		}

		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param NodeList<StatementNode> $stmts */
	public function setStmts(NodeList $stmts): void
	{
		$this->adopt($stmts);
		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
