<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Nodes\StaticVarNode;
use PhpSyntax\Token;


/**
 * static variable declaration.
 */
final class StaticNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<StaticVarNode> $vars
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $staticKeyword,
		public SeparatedNodeList $vars,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->staticKeyword, $this->vars, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->staticKeyword) {
			$this->setStaticKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('staticKeyword', $new));
		} elseif ($old === $this->vars) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('vars', $new);
			}

			/** @var SeparatedNodeList<StaticVarNode> $new  the item type is erased at runtime */
			$this->setVars($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setStaticKeyword(Token $staticKeyword): void
	{
		$this->adopt($staticKeyword);
		$this->release($this->staticKeyword);
		$this->staticKeyword = $staticKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<StaticVarNode> $vars */
	public function setVars(SeparatedNodeList $vars): void
	{
		$this->adopt($vars);
		$this->release($this->vars);
		$this->vars = $vars;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
