<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\CaseNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * switch statement in either syntax; a semicolon may precede the first case.
 */
final class SwitchNode extends StatementNode
{
	/**
	 * @param NodeList<CaseNode> $cases
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $switchKeyword,
		public Token $openParen,
		public ExpressionNode $cond,
		public Token $closeParen,
		public ?Token $openBrace,
		public ?Token $colon,
		public ?Token $leadingSemicolon,
		public NodeList $cases,
		public ?Token $closeBrace,
		public ?Token $endKeyword,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->switchKeyword;
		$children[] = $this->openParen;
		$children[] = $this->cond;
		$children[] = $this->closeParen;
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->leadingSemicolon) {
			$children[] = $this->leadingSemicolon;
		}
		$children[] = $this->cases;
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}
		if ($this->endKeyword) {
			$children[] = $this->endKeyword;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->switchKeyword) {
			$this->setSwitchKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('switchKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->leadingSemicolon) {
			$this->setLeadingSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('leadingSemicolon', $new));
		} elseif ($old === $this->cases) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('cases', $new);
			}

			/** @var NodeList<CaseNode> $new  the item type is erased at runtime */
			$this->setCases($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} elseif ($old === $this->endKeyword) {
			$this->setEndKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('endKeyword', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setSwitchKeyword(Token $switchKeyword): void
	{
		$this->adopt($switchKeyword);
		$this->release($this->switchKeyword);
		$this->switchKeyword = $switchKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setCond(ExpressionNode $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setLeadingSemicolon(?Token $leadingSemicolon): void
	{
		if ($leadingSemicolon) {
			$this->adopt($leadingSemicolon);
		}

		$this->release($this->leadingSemicolon);
		$this->leadingSemicolon = $leadingSemicolon;
		$this->structureChanged();
	}


	/** @param NodeList<CaseNode> $cases */
	public function setCases(NodeList $cases): void
	{
		$this->adopt($cases);
		$this->release($this->cases);
		$this->cases = $cases;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}


	public function setEndKeyword(?Token $endKeyword): void
	{
		if ($endKeyword) {
			$this->adopt($endKeyword);
		}

		$this->release($this->endKeyword);
		$this->endKeyword = $endKeyword;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
