<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ClassLikeNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * Trait declaration.
 */
final class TraitNode extends StatementNode implements ClassLikeNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param NodeList<MemberNode> $members
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public Token $traitKeyword,
		public IdentifierNode $name,
		public Token $openBrace,
		public NodeList $members,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		return [$this->attributes, $this->traitKeyword, $this->name, $this->openBrace, $this->members, $this->closeBrace];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->traitKeyword) {
			$this->setTraitKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('traitKeyword', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->members) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('members', $new);
			}

			/** @var NodeList<MemberNode> $new  the item type is erased at runtime */
			$this->setMembers($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setTraitKeyword(Token $traitKeyword): void
	{
		$this->adopt($traitKeyword);
		$this->release($this->traitKeyword);
		$this->traitKeyword = $traitKeyword;
		$this->structureChanged();
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param NodeList<MemberNode> $members */
	public function setMembers(NodeList $members): void
	{
		$this->adopt($members);
		$this->release($this->members);
		$this->members = $members;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
