<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\CatchNode;
use PhpSyntax\Nodes\FinallyNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * try statement with catches and an optional finally.
 */
final class TryNode extends StatementNode
{
	/**
	 * @param NodeList<CatchNode> $catches
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $tryKeyword,
		public BlockNode $body,
		public NodeList $catches,
		public ?FinallyNode $finally,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->tryKeyword;
		$children[] = $this->body;
		$children[] = $this->catches;
		if ($this->finally) {
			$children[] = $this->finally;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->tryKeyword) {
			$this->setTryKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('tryKeyword', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof BlockNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->catches) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('catches', $new);
			}

			/** @var NodeList<CatchNode> $new  the item type is erased at runtime */
			$this->setCatches($new);
		} elseif ($old === $this->finally) {
			$this->setFinally($new instanceof FinallyNode ? $new : throw self::describeSlotMismatch('finally', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setTryKeyword(Token $tryKeyword): void
	{
		$this->adopt($tryKeyword);
		$this->release($this->tryKeyword);
		$this->tryKeyword = $tryKeyword;
		$this->structureChanged();
	}


	public function setBody(BlockNode $body): void
	{
		$this->adopt($body);
		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	/** @param NodeList<CatchNode> $catches */
	public function setCatches(NodeList $catches): void
	{
		$this->adopt($catches);
		$this->release($this->catches);
		$this->catches = $catches;
		$this->structureChanged();
	}


	public function setFinally(?FinallyNode $finally): void
	{
		if ($finally) {
			$this->adopt($finally);
		}

		$this->release($this->finally);
		$this->finally = $finally;
		$this->structureChanged();
	}
}
