<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Token;


/**
 * unset statement.
 */
final class UnsetNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<ExpressionNode> $vars
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $unsetKeyword,
		public Token $openParen,
		public SeparatedNodeList $vars,
		public Token $closeParen,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->unsetKeyword, $this->openParen, $this->vars, $this->closeParen, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->unsetKeyword) {
			$this->setUnsetKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('unsetKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->vars) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('vars', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setVars($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setUnsetKeyword(Token $unsetKeyword): void
	{
		$this->adopt($unsetKeyword);
		$this->release($this->unsetKeyword);
		$this->unsetKeyword = $unsetKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $vars */
	public function setVars(SeparatedNodeList $vars): void
	{
		$this->adopt($vars);
		$this->release($this->vars);
		$this->vars = $vars;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
