<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Statement;

use PhpSyntax\Node;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\StatementNode;
use PhpSyntax\Nodes\UseItemNode;
use PhpSyntax\Token;


/**
 * use import of classes, functions or constants.
 */
final class UseNode extends StatementNode
{
	/**
	 * @param SeparatedNodeList<UseItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $useKeyword,
		public ?Token $type,
		public SeparatedNodeList $items,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->useKeyword;
		if ($this->type) {
			$children[] = $this->type;
		}
		$children[] = $this->items;
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->useKeyword) {
			$this->setUseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('useKeyword', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof Token ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<UseItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setUseKeyword(Token $useKeyword): void
	{
		$this->adopt($useKeyword);
		$this->release($this->useKeyword);
		$this->useKeyword = $useKeyword;
		$this->structureChanged();
	}


	public function setType(?Token $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<UseItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
