<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Anonymous class in a new expression: new class(...) extends A implements B { ... }.
 */
final class AnonymousClassNode extends Node implements ClassLikeNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param ?SeparatedNodeList<NameNode> $implements
	 * @param NodeList<MemberNode> $members
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public Token $classKeyword,
		public ?ArgumentListNode $args,
		public ?Token $extendsKeyword,
		public ?NameNode $extends,
		public ?Token $implementsKeyword,
		public ?SeparatedNodeList $implements,
		public Token $openBrace,
		public NodeList $members,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		$children[] = $this->classKeyword;
		if ($this->args) {
			$children[] = $this->args;
		}
		if ($this->extendsKeyword) {
			$children[] = $this->extendsKeyword;
		}
		if ($this->extends) {
			$children[] = $this->extends;
		}
		if ($this->implementsKeyword) {
			$children[] = $this->implementsKeyword;
		}
		if ($this->implements) {
			$children[] = $this->implements;
		}
		$children[] = $this->openBrace;
		$children[] = $this->members;
		$children[] = $this->closeBrace;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->classKeyword) {
			$this->setClassKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('classKeyword', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} elseif ($old === $this->extendsKeyword) {
			$this->setExtendsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('extendsKeyword', $new));
		} elseif ($old === $this->extends) {
			$this->setExtends($new instanceof NameNode ? $new : throw self::describeSlotMismatch('extends', $new));
		} elseif ($old === $this->implementsKeyword) {
			$this->setImplementsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('implementsKeyword', $new));
		} elseif ($old === $this->implements) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('implements', $new);
			}

			/** @var SeparatedNodeList<NameNode> $new  the item type is erased at runtime */
			$this->setImplements($new);
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->members) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('members', $new);
			}

			/** @var NodeList<MemberNode> $new  the item type is erased at runtime */
			$this->setMembers($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setClassKeyword(Token $classKeyword): void
	{
		$this->adopt($classKeyword);
		$this->release($this->classKeyword);
		$this->classKeyword = $classKeyword;
		$this->structureChanged();
	}


	public function setArgs(?ArgumentListNode $args): void
	{
		if ($args) {
			$this->adopt($args);
		}

		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}


	public function setExtendsKeyword(?Token $extendsKeyword): void
	{
		if ($extendsKeyword) {
			$this->adopt($extendsKeyword);
		}

		$this->release($this->extendsKeyword);
		$this->extendsKeyword = $extendsKeyword;
		$this->structureChanged();
	}


	public function setExtends(?NameNode $extends): void
	{
		if ($extends) {
			$this->adopt($extends);
		}

		$this->release($this->extends);
		$this->extends = $extends;
		$this->structureChanged();
	}


	public function setImplementsKeyword(?Token $implementsKeyword): void
	{
		if ($implementsKeyword) {
			$this->adopt($implementsKeyword);
		}

		$this->release($this->implementsKeyword);
		$this->implementsKeyword = $implementsKeyword;
		$this->structureChanged();
	}


	/** @param ?SeparatedNodeList<NameNode> $implements */
	public function setImplements(?SeparatedNodeList $implements): void
	{
		if ($implements) {
			$this->adopt($implements);
		}

		$this->release($this->implements);
		$this->implements = $implements;
		$this->structureChanged();
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param NodeList<MemberNode> $members */
	public function setMembers(NodeList $members): void
	{
		$this->adopt($members);
		$this->release($this->members);
		$this->members = $members;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
