<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Parenthesized arguments of a call, instantiation, attribute or exit.
 */
final class ArgumentListNode extends Node
{
	/**
	 * @param SeparatedNodeList<ArgumentNode|VariadicPlaceholderNode> $args
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openParen,
		public SeparatedNodeList $args,
		public Token $closeParen,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openParen, $this->args, $this->closeParen];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->args) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('args', $new);
			}

			/** @var SeparatedNodeList<ArgumentNode|VariadicPlaceholderNode> $new  the item type is erased at runtime */
			$this->setArgs($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ArgumentNode|VariadicPlaceholderNode> $args */
	public function setArgs(SeparatedNodeList $args): void
	{
		$this->adopt($args);
		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}
}
