<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Argument of a call: optionally named, by reference or unpacked.
 */
final class ArgumentNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?IdentifierNode $name,
		public ?Token $colon,
		public ?Token $byRef,
		public ?Token $ellipsis,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->name) {
			$children[] = $this->name;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		if ($this->ellipsis) {
			$children[] = $this->ellipsis;
		}
		$children[] = $this->expr;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->ellipsis) {
			$this->setEllipsis($new instanceof Token ? $new : throw self::describeSlotMismatch('ellipsis', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(?IdentifierNode $name): void
	{
		if ($name) {
			$this->adopt($name);
		}

		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setEllipsis(?Token $ellipsis): void
	{
		if ($ellipsis) {
			$this->adopt($ellipsis);
		}

		$this->release($this->ellipsis);
		$this->ellipsis = $ellipsis;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
