<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Item of an array literal or a destructuring list: value with optional key, by reference or unpacked.
 */
final class ArrayItemNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?ExpressionNode $key,
		public ?Token $doubleArrow,
		public ?Token $byRef,
		public ?Token $ellipsis,
		public ExpressionNode $value,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->key) {
			$children[] = $this->key;
		}
		if ($this->doubleArrow) {
			$children[] = $this->doubleArrow;
		}
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		if ($this->ellipsis) {
			$children[] = $this->ellipsis;
		}
		$children[] = $this->value;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->key) {
			$this->setKey($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('key', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->ellipsis) {
			$this->setEllipsis($new instanceof Token ? $new : throw self::describeSlotMismatch('ellipsis', $new));
		} elseif ($old === $this->value) {
			$this->setValue($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('value', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setKey(?ExpressionNode $key): void
	{
		if ($key) {
			$this->adopt($key);
		}

		$this->release($this->key);
		$this->key = $key;
		$this->structureChanged();
	}


	public function setDoubleArrow(?Token $doubleArrow): void
	{
		if ($doubleArrow) {
			$this->adopt($doubleArrow);
		}

		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setEllipsis(?Token $ellipsis): void
	{
		if ($ellipsis) {
			$this->adopt($ellipsis);
		}

		$this->release($this->ellipsis);
		$this->ellipsis = $ellipsis;
		$this->structureChanged();
	}


	public function setValue(ExpressionNode $value): void
	{
		$this->adopt($value);
		$this->release($this->value);
		$this->value = $value;
		$this->structureChanged();
	}
}
