<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Attribute with optional arguments.
 */
final class AttributeNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode $name,
		public ?ArgumentListNode $args,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->name;
		if ($this->args) {
			$children[] = $this->args;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof NameNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(NameNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setArgs(?ArgumentListNode $args): void
	{
		if ($args) {
			$this->adopt($args);
		}

		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}
}
