<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * One #[...] group of attributes.
 */
final class AttributeGroupNode extends Node
{
	/**
	 * @param SeparatedNodeList<AttributeNode> $attributes
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openAttribute,
		public SeparatedNodeList $attributes,
		public Token $closeBracket,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openAttribute, $this->attributes, $this->closeBracket];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openAttribute) {
			$this->setOpenAttribute($new instanceof Token ? $new : throw self::describeSlotMismatch('openAttribute', $new));
		} elseif ($old === $this->attributes) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var SeparatedNodeList<AttributeNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->closeBracket) {
			$this->setCloseBracket($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBracket', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenAttribute(Token $openAttribute): void
	{
		$this->adopt($openAttribute);
		$this->release($this->openAttribute);
		$this->openAttribute = $openAttribute;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<AttributeNode> $attributes */
	public function setAttributes(SeparatedNodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setCloseBracket(Token $closeBracket): void
	{
		$this->adopt($closeBracket);
		$this->release($this->closeBracket);
		$this->closeBracket = $closeBracket;
		$this->structureChanged();
	}
}
