<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * case or default of a switch; the separator is a colon or a semicolon.
 */
final class CaseNode extends Node
{
	/**
	 * @param NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $caseKeyword,
		public ?ExpressionNode $cond,
		public Token $separator,
		public NodeList $stmts,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->caseKeyword;
		if ($this->cond) {
			$children[] = $this->cond;
		}
		$children[] = $this->separator;
		$children[] = $this->stmts;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->caseKeyword) {
			$this->setCaseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('caseKeyword', $new));
		} elseif ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->separator) {
			$this->setSeparator($new instanceof Token ? $new : throw self::describeSlotMismatch('separator', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setCaseKeyword(Token $caseKeyword): void
	{
		$this->adopt($caseKeyword);
		$this->release($this->caseKeyword);
		$this->caseKeyword = $caseKeyword;
		$this->structureChanged();
	}


	public function setCond(?ExpressionNode $cond): void
	{
		if ($cond) {
			$this->adopt($cond);
		}

		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setSeparator(Token $separator): void
	{
		$this->adopt($separator);
		$this->release($this->separator);
		$this->separator = $separator;
		$this->structureChanged();
	}


	/** @param NodeList<StatementNode> $stmts */
	public function setStmts(NodeList $stmts): void
	{
		$this->adopt($stmts);
		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}
}
