<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Nodes\Expression\VariableNode;
use PhpSyntax\Nodes\Statement\BlockNode;
use PhpSyntax\Token;


/**
 * catch clause with one or more types and an optional variable.
 */
final class CatchNode extends Node
{
	/**
	 * @param SeparatedNodeList<NameNode> $types
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $catchKeyword,
		public Token $openParen,
		public SeparatedNodeList $types,
		public ?VariableNode $var,
		public Token $closeParen,
		public BlockNode $body,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->catchKeyword;
		$children[] = $this->openParen;
		$children[] = $this->types;
		if ($this->var) {
			$children[] = $this->var;
		}
		$children[] = $this->closeParen;
		$children[] = $this->body;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->catchKeyword) {
			$this->setCatchKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('catchKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->types) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('types', $new);
			}

			/** @var SeparatedNodeList<NameNode> $new  the item type is erased at runtime */
			$this->setTypes($new);
		} elseif ($old === $this->var) {
			$this->setVar($new instanceof VariableNode ? $new : throw self::describeSlotMismatch('var', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof BlockNode ? $new : throw self::describeSlotMismatch('body', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setCatchKeyword(Token $catchKeyword): void
	{
		$this->adopt($catchKeyword);
		$this->release($this->catchKeyword);
		$this->catchKeyword = $catchKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<NameNode> $types */
	public function setTypes(SeparatedNodeList $types): void
	{
		$this->adopt($types);
		$this->release($this->types);
		$this->types = $types;
		$this->structureChanged();
	}


	public function setVar(?VariableNode $var): void
	{
		if ($var) {
			$this->adopt($var);
		}

		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setBody(BlockNode $body): void
	{
		$this->adopt($body);
		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}
}
