<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Nodes\Expression\VariableNode;
use PhpSyntax\Token;


/**
 * Variable captured by a closure, optionally by reference.
 */
final class ClosureUseNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?Token $byRef,
		public VariableNode $var,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		$children[] = $this->var;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->var) {
			$this->setVar($new instanceof VariableNode ? $new : throw self::describeSlotMismatch('var', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setVar(VariableNode $var): void
	{
		$this->adopt($var);
		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}
}
