<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * The use (...) clause of a closure.
 */
final class ClosureUsesNode extends Node
{
	/**
	 * @param SeparatedNodeList<ClosureUseNode> $vars
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $useKeyword,
		public Token $openParen,
		public SeparatedNodeList $vars,
		public Token $closeParen,
	) {
	}


	public function getChildren(): array
	{
		return [$this->useKeyword, $this->openParen, $this->vars, $this->closeParen];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->useKeyword) {
			$this->setUseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('useKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->vars) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('vars', $new);
			}

			/** @var SeparatedNodeList<ClosureUseNode> $new  the item type is erased at runtime */
			$this->setVars($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setUseKeyword(Token $useKeyword): void
	{
		$this->adopt($useKeyword);
		$this->release($this->useKeyword);
		$this->useKeyword = $useKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ClosureUseNode> $vars */
	public function setVars(SeparatedNodeList $vars): void
	{
		$this->adopt($vars);
		$this->release($this->vars);
		$this->vars = $vars;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}
}
