<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Constant of a const statement or a class constant declaration.
 */
final class ConstItemNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public IdentifierNode $name,
		public Token $equals,
		public ExpressionNode $value,
	) {
	}


	public function getChildren(): array
	{
		return [$this->name, $this->equals, $this->value];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->value) {
			$this->setValue($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('value', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setEquals(Token $equals): void
	{
		$this->adopt($equals);
		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setValue(ExpressionNode $value): void
	{
		$this->adopt($value);
		$this->release($this->value);
		$this->value = $value;
		$this->structureChanged();
	}
}
