<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * else branch, in either syntax; else if is an else with an if statement as the body.
 */
final class ElseNode extends Node
{
	/**
	 * @param ?NodeList<StatementNode> $stmts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $elseKeyword,
		public ?StatementNode $body,
		public ?Token $colon,
		public ?NodeList $stmts,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->elseKeyword;
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->stmts) {
			$children[] = $this->stmts;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->elseKeyword) {
			$this->setElseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('elseKeyword', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof StatementNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->stmts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('stmts', $new);
			}

			/** @var NodeList<StatementNode> $new  the item type is erased at runtime */
			$this->setStmts($new);
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setElseKeyword(Token $elseKeyword): void
	{
		$this->adopt($elseKeyword);
		$this->release($this->elseKeyword);
		$this->elseKeyword = $elseKeyword;
		$this->structureChanged();
	}


	public function setBody(?StatementNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	/** @param ?NodeList<StatementNode> $stmts */
	public function setStmts(?NodeList $stmts): void
	{
		if ($stmts) {
			$this->adopt($stmts);
		}

		$this->release($this->stmts);
		$this->stmts = $stmts;
		$this->structureChanged();
	}
}
