<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Skipped item of a destructuring list ([, $b] = $x); has no tokens.
 */
final class EmptyArrayItemNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct()
	{
	}


	public function getChildren(): array
	{
		return [];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		
		throw self::describeChildMismatch($old);
	}
}
