<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Nodes\Statement\BlockNode;
use PhpSyntax\Token;


/**
 * finally clause.
 */
final class FinallyNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $finallyKeyword,
		public BlockNode $body,
	) {
	}


	public function getChildren(): array
	{
		return [$this->finallyKeyword, $this->body];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->finallyKeyword) {
			$this->setFinallyKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('finallyKeyword', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof BlockNode ? $new : throw self::describeSlotMismatch('body', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setFinallyKeyword(Token $finallyKeyword): void
	{
		$this->adopt($finallyKeyword);
		$this->release($this->finallyKeyword);
		$this->finallyKeyword = $finallyKeyword;
		$this->structureChanged();
	}


	public function setBody(BlockNode $body): void
	{
		$this->adopt($body);
		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}
}
