<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Identifier of a member, label, hook or alias: one token of any kind, including reserved words.
 */
final class IdentifierNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $token,
	) {
	}


	public function getChildren(): array
	{
		return [$this->token];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->token) {
			$this->setToken($new instanceof Token ? $new : throw self::describeSlotMismatch('token', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setToken(Token $token): void
	{
		$this->adopt($token);
		$this->release($this->token);
		$this->token = $token;
		$this->structureChanged();
	}
}
