<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Arm of a match expression: conditions or default, and the result.
 */
final class MatchArmNode extends Node
{
	/**
	 * @param ?SeparatedNodeList<ExpressionNode> $conds
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?SeparatedNodeList $conds,
		public ?Token $defaultKeyword,
		public ?Token $defaultComma,
		public Token $doubleArrow,
		public ExpressionNode $body,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->conds) {
			$children[] = $this->conds;
		}
		if ($this->defaultKeyword) {
			$children[] = $this->defaultKeyword;
		}
		if ($this->defaultComma) {
			$children[] = $this->defaultComma;
		}
		$children[] = $this->doubleArrow;
		$children[] = $this->body;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->conds) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('conds', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setConds($new);
		} elseif ($old === $this->defaultKeyword) {
			$this->setDefaultKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('defaultKeyword', $new));
		} elseif ($old === $this->defaultComma) {
			$this->setDefaultComma($new instanceof Token ? $new : throw self::describeSlotMismatch('defaultComma', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('body', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param ?SeparatedNodeList<ExpressionNode> $conds */
	public function setConds(?SeparatedNodeList $conds): void
	{
		if ($conds) {
			$this->adopt($conds);
		}

		$this->release($this->conds);
		$this->conds = $conds;
		$this->structureChanged();
	}


	public function setDefaultKeyword(?Token $defaultKeyword): void
	{
		if ($defaultKeyword) {
			$this->adopt($defaultKeyword);
		}

		$this->release($this->defaultKeyword);
		$this->defaultKeyword = $defaultKeyword;
		$this->structureChanged();
	}


	public function setDefaultComma(?Token $defaultComma): void
	{
		if ($defaultComma) {
			$this->adopt($defaultComma);
		}

		$this->release($this->defaultComma);
		$this->defaultComma = $defaultComma;
		$this->structureChanged();
	}


	public function setDoubleArrow(Token $doubleArrow): void
	{
		$this->adopt($doubleArrow);
		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setBody(ExpressionNode $body): void
	{
		$this->adopt($body);
		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}
}
