<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Nodes\Expression\VariableNode;
use PhpSyntax\Nodes\Member\PropertyHookNode;
use PhpSyntax\Token;


/**
 * Parameter of a function, method, closure or hook; with modifiers it promotes a property.
 */
final class ParameterNode extends Node
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param ?NodeList<PropertyHookNode> $hooks
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public ?TypeNode $type,
		public ?Token $byRef,
		public ?Token $ellipsis,
		public VariableNode $var,
		public ?Token $equals,
		public ?ExpressionNode $default,
		public ?Token $openBrace,
		public ?NodeList $hooks,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		if ($this->type) {
			$children[] = $this->type;
		}
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		if ($this->ellipsis) {
			$children[] = $this->ellipsis;
		}
		$children[] = $this->var;
		if ($this->equals) {
			$children[] = $this->equals;
		}
		if ($this->default) {
			$children[] = $this->default;
		}
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		if ($this->hooks) {
			$children[] = $this->hooks;
		}
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->ellipsis) {
			$this->setEllipsis($new instanceof Token ? $new : throw self::describeSlotMismatch('ellipsis', $new));
		} elseif ($old === $this->var) {
			$this->setVar($new instanceof VariableNode ? $new : throw self::describeSlotMismatch('var', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->default) {
			$this->setDefault($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('default', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->hooks) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('hooks', $new);
			}

			/** @var NodeList<PropertyHookNode> $new  the item type is erased at runtime */
			$this->setHooks($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setType(?TypeNode $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setEllipsis(?Token $ellipsis): void
	{
		if ($ellipsis) {
			$this->adopt($ellipsis);
		}

		$this->release($this->ellipsis);
		$this->ellipsis = $ellipsis;
		$this->structureChanged();
	}


	public function setVar(VariableNode $var): void
	{
		$this->adopt($var);
		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}


	public function setEquals(?Token $equals): void
	{
		if ($equals) {
			$this->adopt($equals);
		}

		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setDefault(?ExpressionNode $default): void
	{
		if ($default) {
			$this->adopt($default);
		}

		$this->release($this->default);
		$this->default = $default;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param ?NodeList<PropertyHookNode> $hooks */
	public function setHooks(?NodeList $hooks): void
	{
		if ($hooks) {
			$this->adopt($hooks);
		}

		$this->release($this->hooks);
		$this->hooks = $hooks;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
