<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Nodes\Expression\VariableNode;
use PhpSyntax\Token;


/**
 * Variable of a static statement with an optional initializer.
 */
final class StaticVarNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public VariableNode $var,
		public ?Token $equals,
		public ?ExpressionNode $default,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->var;
		if ($this->equals) {
			$children[] = $this->equals;
		}
		if ($this->default) {
			$children[] = $this->default;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->var) {
			$this->setVar($new instanceof VariableNode ? $new : throw self::describeSlotMismatch('var', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->default) {
			$this->setDefault($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('default', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setVar(VariableNode $var): void
	{
		$this->adopt($var);
		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}


	public function setEquals(?Token $equals): void
	{
		if ($equals) {
			$this->adopt($equals);
		}

		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setDefault(?ExpressionNode $default): void
	{
		if ($default) {
			$this->adopt($default);
		}

		$this->release($this->default);
		$this->default = $default;
		$this->structureChanged();
	}
}
