<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Imported name with an optional alias; the type (function, const) appears only inside a group use.
 */
final class UseItemNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?Token $type,
		public NameNode $name,
		public ?Token $asKeyword,
		public ?IdentifierNode $alias,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->type) {
			$children[] = $this->type;
		}
		$children[] = $this->name;
		if ($this->asKeyword) {
			$children[] = $this->asKeyword;
		}
		if ($this->alias) {
			$children[] = $this->alias;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->type) {
			$this->setType($new instanceof Token ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof NameNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->asKeyword) {
			$this->setAsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('asKeyword', $new));
		} elseif ($old === $this->alias) {
			$this->setAlias($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('alias', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setType(?Token $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	public function setName(NameNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setAsKeyword(?Token $asKeyword): void
	{
		if ($asKeyword) {
			$this->adopt($asKeyword);
		}

		$this->release($this->asKeyword);
		$this->asKeyword = $asKeyword;
		$this->structureChanged();
	}


	public function setAlias(?IdentifierNode $alias): void
	{
		if ($alias) {
			$this->adopt($alias);
		}

		$this->release($this->alias);
		$this->alias = $alias;
		$this->structureChanged();
	}
}
