<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * The ... placeholder of a first-class callable: f(...).
 */
final class VariadicPlaceholderNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $ellipsis,
	) {
	}


	public function getChildren(): array
	{
		return [$this->ellipsis];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->ellipsis) {
			$this->setEllipsis($new instanceof Token ? $new : throw self::describeSlotMismatch('ellipsis', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setEllipsis(Token $ellipsis): void
	{
		$this->adopt($ellipsis);
		$this->release($this->ellipsis);
		$this->ellipsis = $ellipsis;
		$this->structureChanged();
	}
}
