<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ConstItemNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\ModifiersNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Class constant declaration, optionally typed.
 */
final class ClassConstNode extends MemberNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param SeparatedNodeList<ConstItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public Token $constKeyword,
		public ?TypeNode $type,
		public SeparatedNodeList $items,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		$children[] = $this->constKeyword;
		if ($this->type) {
			$children[] = $this->type;
		}
		$children[] = $this->items;
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->constKeyword) {
			$this->setConstKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('constKeyword', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<ConstItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setConstKeyword(Token $constKeyword): void
	{
		$this->adopt($constKeyword);
		$this->release($this->constKeyword);
		$this->constKeyword = $constKeyword;
		$this->structureChanged();
	}


	public function setType(?TypeNode $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ConstItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
