<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Token;


/**
 * Enum case with an optional backing value.
 */
final class EnumCaseNode extends MemberNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public Token $caseKeyword,
		public IdentifierNode $name,
		public ?Token $equals,
		public ?ExpressionNode $value,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->caseKeyword;
		$children[] = $this->name;
		if ($this->equals) {
			$children[] = $this->equals;
		}
		if ($this->value) {
			$children[] = $this->value;
		}
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->caseKeyword) {
			$this->setCaseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('caseKeyword', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->value) {
			$this->setValue($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('value', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setCaseKeyword(Token $caseKeyword): void
	{
		$this->adopt($caseKeyword);
		$this->release($this->caseKeyword);
		$this->caseKeyword = $caseKeyword;
		$this->structureChanged();
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setEquals(?Token $equals): void
	{
		if ($equals) {
			$this->adopt($equals);
		}

		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setValue(?ExpressionNode $value): void
	{
		if ($value) {
			$this->adopt($value);
		}

		$this->release($this->value);
		$this->value = $value;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
