<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\ModifiersNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\ParameterNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\Statement\BlockNode;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Method declaration; abstract and interface methods end with a semicolon instead of a body.
 */
final class MethodNode extends MemberNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param SeparatedNodeList<ParameterNode> $params
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public Token $functionKeyword,
		public ?Token $byRef,
		public IdentifierNode $name,
		public Token $openParen,
		public SeparatedNodeList $params,
		public Token $closeParen,
		public ?Token $colon,
		public ?TypeNode $returnType,
		public ?BlockNode $body,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		$children[] = $this->functionKeyword;
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		$children[] = $this->name;
		$children[] = $this->openParen;
		$children[] = $this->params;
		$children[] = $this->closeParen;
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->returnType) {
			$children[] = $this->returnType;
		}
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->functionKeyword) {
			$this->setFunctionKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('functionKeyword', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->params) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('params', $new);
			}

			/** @var SeparatedNodeList<ParameterNode> $new  the item type is erased at runtime */
			$this->setParams($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->returnType) {
			$this->setReturnType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('returnType', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof BlockNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setFunctionKeyword(Token $functionKeyword): void
	{
		$this->adopt($functionKeyword);
		$this->release($this->functionKeyword);
		$this->functionKeyword = $functionKeyword;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ParameterNode> $params */
	public function setParams(SeparatedNodeList $params): void
	{
		$this->adopt($params);
		$this->release($this->params);
		$this->params = $params;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setReturnType(?TypeNode $returnType): void
	{
		if ($returnType) {
			$this->adopt($returnType);
		}

		$this->release($this->returnType);
		$this->returnType = $returnType;
		$this->structureChanged();
	}


	public function setBody(?BlockNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
