<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * One property of a declaration with an optional default.
 */
final class PropertyItemNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $name,
		public ?Token $equals,
		public ?ExpressionNode $default,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->name;
		if ($this->equals) {
			$children[] = $this->equals;
		}
		if ($this->default) {
			$children[] = $this->default;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof Token ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->default) {
			$this->setDefault($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('default', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(Token $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setEquals(?Token $equals): void
	{
		if ($equals) {
			$this->adopt($equals);
		}

		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setDefault(?ExpressionNode $default): void
	{
		if ($default) {
			$this->adopt($default);
		}

		$this->release($this->default);
		$this->default = $default;
		$this->structureChanged();
	}
}
