<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\ModifiersNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Property declaration; one or more properties, optionally with hooks.
 */
final class PropertyNode extends MemberNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param SeparatedNodeList<PropertyItemNode> $items
	 * @param ?NodeList<PropertyHookNode> $hooks
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public ?TypeNode $type,
		public SeparatedNodeList $items,
		public ?Token $semicolon,
		public ?Token $openBrace,
		public ?NodeList $hooks,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		if ($this->type) {
			$children[] = $this->type;
		}
		$children[] = $this->items;
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		if ($this->hooks) {
			$children[] = $this->hooks;
		}
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('type', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<PropertyItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->hooks) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('hooks', $new);
			}

			/** @var NodeList<PropertyHookNode> $new  the item type is erased at runtime */
			$this->setHooks($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setType(?TypeNode $type): void
	{
		if ($type) {
			$this->adopt($type);
		}

		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<PropertyItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param ?NodeList<PropertyHookNode> $hooks */
	public function setHooks(?NodeList $hooks): void
	{
		if ($hooks) {
			$this->adopt($hooks);
		}

		$this->release($this->hooks);
		$this->hooks = $hooks;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
