<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\ModifiersNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\ParameterNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\Statement\BlockNode;
use PhpSyntax\Token;


/**
 * Property hook (get, set) with a block body, an arrow body or none.
 */
final class PropertyHookNode extends Node
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param ?SeparatedNodeList<ParameterNode> $params
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ModifiersNode $modifiers,
		public ?Token $byRef,
		public IdentifierNode $name,
		public ?Token $openParen,
		public ?SeparatedNodeList $params,
		public ?Token $closeParen,
		public ?BlockNode $body,
		public ?Token $doubleArrow,
		public ?ExpressionNode $expr,
		public ?Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		$children[] = $this->modifiers;
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		$children[] = $this->name;
		if ($this->openParen) {
			$children[] = $this->openParen;
		}
		if ($this->params) {
			$children[] = $this->params;
		}
		if ($this->closeParen) {
			$children[] = $this->closeParen;
		}
		if ($this->body) {
			$children[] = $this->body;
		}
		if ($this->doubleArrow) {
			$children[] = $this->doubleArrow;
		}
		if ($this->expr) {
			$children[] = $this->expr;
		}
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->modifiers) {
			$this->setModifiers($new instanceof ModifiersNode ? $new : throw self::describeSlotMismatch('modifiers', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->params) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('params', $new);
			}

			/** @var SeparatedNodeList<ParameterNode> $new  the item type is erased at runtime */
			$this->setParams($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->body) {
			$this->setBody($new instanceof BlockNode ? $new : throw self::describeSlotMismatch('body', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setModifiers(ModifiersNode $modifiers): void
	{
		$this->adopt($modifiers);
		$this->release($this->modifiers);
		$this->modifiers = $modifiers;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setName(IdentifierNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setOpenParen(?Token $openParen): void
	{
		if ($openParen) {
			$this->adopt($openParen);
		}

		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param ?SeparatedNodeList<ParameterNode> $params */
	public function setParams(?SeparatedNodeList $params): void
	{
		if ($params) {
			$this->adopt($params);
		}

		$this->release($this->params);
		$this->params = $params;
		$this->structureChanged();
	}


	public function setCloseParen(?Token $closeParen): void
	{
		if ($closeParen) {
			$this->adopt($closeParen);
		}

		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setBody(?BlockNode $body): void
	{
		if ($body) {
			$this->adopt($body);
		}

		$this->release($this->body);
		$this->body = $body;
		$this->structureChanged();
	}


	public function setDoubleArrow(?Token $doubleArrow): void
	{
		if ($doubleArrow) {
			$this->adopt($doubleArrow);
		}

		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setExpr(?ExpressionNode $expr): void
	{
		if ($expr) {
			$this->adopt($expr);
		}

		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
