<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\MemberNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * use of traits with optional adaptations in braces.
 */
final class TraitUseNode extends MemberNode
{
	/**
	 * @param SeparatedNodeList<NameNode> $traits
	 * @param ?NodeList<TraitPrecedenceNode|TraitAliasNode> $adaptations
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $useKeyword,
		public SeparatedNodeList $traits,
		public ?Token $semicolon,
		public ?Token $openBrace,
		public ?NodeList $adaptations,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->useKeyword;
		$children[] = $this->traits;
		if ($this->semicolon) {
			$children[] = $this->semicolon;
		}
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		if ($this->adaptations) {
			$children[] = $this->adaptations;
		}
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->useKeyword) {
			$this->setUseKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('useKeyword', $new));
		} elseif ($old === $this->traits) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('traits', $new);
			}

			/** @var SeparatedNodeList<NameNode> $new  the item type is erased at runtime */
			$this->setTraits($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->adaptations) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('adaptations', $new);
			}

			/** @var NodeList<TraitPrecedenceNode|TraitAliasNode> $new  the item type is erased at runtime */
			$this->setAdaptations($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setUseKeyword(Token $useKeyword): void
	{
		$this->adopt($useKeyword);
		$this->release($this->useKeyword);
		$this->useKeyword = $useKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<NameNode> $traits */
	public function setTraits(SeparatedNodeList $traits): void
	{
		$this->adopt($traits);
		$this->release($this->traits);
		$this->traits = $traits;
		$this->structureChanged();
	}


	public function setSemicolon(?Token $semicolon): void
	{
		if ($semicolon) {
			$this->adopt($semicolon);
		}

		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param ?NodeList<TraitPrecedenceNode|TraitAliasNode> $adaptations */
	public function setAdaptations(?NodeList $adaptations): void
	{
		if ($adaptations) {
			$this->adopt($adaptations);
		}

		$this->release($this->adaptations);
		$this->adaptations = $adaptations;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
