<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * Trait adaptation A::m insteadof B;.
 */
final class TraitPrecedenceNode extends Node
{
	/**
	 * @param SeparatedNodeList<NameNode> $traits
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode $trait,
		public Token $doubleColon,
		public IdentifierNode $method,
		public Token $insteadofKeyword,
		public SeparatedNodeList $traits,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		return [$this->trait, $this->doubleColon, $this->method, $this->insteadofKeyword, $this->traits, $this->semicolon];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->trait) {
			$this->setTrait($new instanceof NameNode ? $new : throw self::describeSlotMismatch('trait', $new));
		} elseif ($old === $this->doubleColon) {
			$this->setDoubleColon($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleColon', $new));
		} elseif ($old === $this->method) {
			$this->setMethod($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('method', $new));
		} elseif ($old === $this->insteadofKeyword) {
			$this->setInsteadofKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('insteadofKeyword', $new));
		} elseif ($old === $this->traits) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('traits', $new);
			}

			/** @var SeparatedNodeList<NameNode> $new  the item type is erased at runtime */
			$this->setTraits($new);
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setTrait(NameNode $trait): void
	{
		$this->adopt($trait);
		$this->release($this->trait);
		$this->trait = $trait;
		$this->structureChanged();
	}


	public function setDoubleColon(Token $doubleColon): void
	{
		$this->adopt($doubleColon);
		$this->release($this->doubleColon);
		$this->doubleColon = $doubleColon;
		$this->structureChanged();
	}


	public function setMethod(IdentifierNode $method): void
	{
		$this->adopt($method);
		$this->release($this->method);
		$this->method = $method;
		$this->structureChanged();
	}


	public function setInsteadofKeyword(Token $insteadofKeyword): void
	{
		$this->adopt($insteadofKeyword);
		$this->release($this->insteadofKeyword);
		$this->insteadofKeyword = $insteadofKeyword;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<NameNode> $traits */
	public function setTraits(SeparatedNodeList $traits): void
	{
		$this->adopt($traits);
		$this->release($this->traits);
		$this->traits = $traits;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
