<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Member;

use PhpSyntax\Node;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Trait adaptation m as [modifier] [alias];.
 */
final class TraitAliasNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?NameNode $trait,
		public ?Token $doubleColon,
		public IdentifierNode $method,
		public Token $asKeyword,
		public ?Token $modifier,
		public ?IdentifierNode $alias,
		public Token $semicolon,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->trait) {
			$children[] = $this->trait;
		}
		if ($this->doubleColon) {
			$children[] = $this->doubleColon;
		}
		$children[] = $this->method;
		$children[] = $this->asKeyword;
		if ($this->modifier) {
			$children[] = $this->modifier;
		}
		if ($this->alias) {
			$children[] = $this->alias;
		}
		$children[] = $this->semicolon;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->trait) {
			$this->setTrait($new instanceof NameNode ? $new : throw self::describeSlotMismatch('trait', $new));
		} elseif ($old === $this->doubleColon) {
			$this->setDoubleColon($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleColon', $new));
		} elseif ($old === $this->method) {
			$this->setMethod($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('method', $new));
		} elseif ($old === $this->asKeyword) {
			$this->setAsKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('asKeyword', $new));
		} elseif ($old === $this->modifier) {
			$this->setModifier($new instanceof Token ? $new : throw self::describeSlotMismatch('modifier', $new));
		} elseif ($old === $this->alias) {
			$this->setAlias($new instanceof IdentifierNode ? $new : throw self::describeSlotMismatch('alias', $new));
		} elseif ($old === $this->semicolon) {
			$this->setSemicolon($new instanceof Token ? $new : throw self::describeSlotMismatch('semicolon', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setTrait(?NameNode $trait): void
	{
		if ($trait) {
			$this->adopt($trait);
		}

		$this->release($this->trait);
		$this->trait = $trait;
		$this->structureChanged();
	}


	public function setDoubleColon(?Token $doubleColon): void
	{
		if ($doubleColon) {
			$this->adopt($doubleColon);
		}

		$this->release($this->doubleColon);
		$this->doubleColon = $doubleColon;
		$this->structureChanged();
	}


	public function setMethod(IdentifierNode $method): void
	{
		$this->adopt($method);
		$this->release($this->method);
		$this->method = $method;
		$this->structureChanged();
	}


	public function setAsKeyword(Token $asKeyword): void
	{
		$this->adopt($asKeyword);
		$this->release($this->asKeyword);
		$this->asKeyword = $asKeyword;
		$this->structureChanged();
	}


	public function setModifier(?Token $modifier): void
	{
		if ($modifier) {
			$this->adopt($modifier);
		}

		$this->release($this->modifier);
		$this->modifier = $modifier;
		$this->structureChanged();
	}


	public function setAlias(?IdentifierNode $alias): void
	{
		if ($alias) {
			$this->adopt($alias);
		}

		$this->release($this->alias);
		$this->alias = $alias;
		$this->structureChanged();
	}


	public function setSemicolon(Token $semicolon): void
	{
		$this->adopt($semicolon);
		$this->release($this->semicolon);
		$this->semicolon = $semicolon;
		$this->structureChanged();
	}
}
