<?php declare(strict_types=1);

/**
 * Ported from Latte grammar/rebuildParsers.php (https://latte.nette.org), itself a port of nikic/php-parser grammar/rebuildParsers.php.
 *
 * Generates src/PhpSyntax/Parser/ParserData.php and src/PhpSyntax/TokenKind.php from grammar/php.y.
 * Options: --debug (keeps y.output and the preprocessed grammar), --strip-actions (removes all actions from php.y).
 */

require __DIR__ . '/phpyLang.php';

chdir(__DIR__); // phpyacc writes y.output to the working directory
$grammarFile = __DIR__ . '/php.y';
$phpyacc = __DIR__ . '/vendor/bin/phpyacc';
$tmpGrammarFile = __DIR__ . '/tmp_parser.phpy';
$tmpResultFile = __DIR__ . '/tmp_parser.php';
$srcDir = __DIR__ . '/../src/PhpSyntax';

$options = array_flip(array_slice($argv, 1));
$optionDebug = isset($options['--debug']);

if (isset($options['--strip-actions'])) {
	$grammar = file_get_contents($grammarFile);
	$grammar = stripActions($grammar);
	file_put_contents($grammarFile, $grammar);
	echo "Actions removed from php.y\n";
	exit;
}


///////////////////
/// Main script ///
///////////////////

$grammar = file_get_contents($grammarFile);
$grammar = preprocessGrammar($grammar);
file_put_contents($tmpGrammarFile, $grammar);

echo "Building parser.\n";
execCmd("$phpyacc " . ($optionDebug ? '-t -v ' : '') . '-m ' . __DIR__ . "/parser.template -p ParserData $tmpGrammarFile");
$code = file_get_contents($tmpResultFile);
$code = removeTrailingWhitespace($code);
file_put_contents("$srcDir/Parser/ParserData.php", $code);
unlink($tmpResultFile);

echo "Building token kinds.\n";
execCmd("$phpyacc -m " . __DIR__ . "/tokens.template $tmpGrammarFile");
$code = buildTokenKind(file_get_contents($tmpResultFile));
file_put_contents("$srcDir/TokenKind.php", $code);
unlink($tmpResultFile);

if (!$optionDebug) {
	unlink($tmpGrammarFile);
}


////////////////////////////////
/// Utility helper functions ///
////////////////////////////////

function execCmd(string $cmd): void
{
	$output = trim((string) shell_exec(PHP_BINARY . ' -d error_reporting=' . (E_ALL & ~E_DEPRECATED) . " $cmd 2>&1"));
	if ($output !== '') {
		echo '> ' . $cmd . "\n";
		echo $output, "\n";
	}
}


/**
 * Removes all semantic actions ({ ... } blocks) from the grammar, keeping quoted tokens like '{' intact.
 */
function stripActions(string $grammar): string
{
	$grammar = preg_replace(regex('(?&string)(*SKIP)(*FAIL)|(?&code)'), '', $grammar);
	$grammar = removeTrailingWhitespace($grammar);
	return preg_replace('~\n\n+(?=[ \t]*[|;])~', "\n", $grammar);
}


/**
 * Turns the "T_NAME = number" list produced by tokens.template into the TokenKind class.
 */
function buildTokenKind(string $list): string
{
	$renames = [
		'Lnumber' => 'Integer',
		'Dnumber' => 'Float',
		'String' => 'Identifier',
		'DoubleCast' => 'FloatCast',
		'PaamayimNekudotayim' => 'DoubleColon',
		'NsSeparator' => 'NamespaceSeparator',
		'Sl' => 'ShiftLeft',
		'Sr' => 'ShiftRight',
		'SlEqual' => 'ShiftLeftEqual',
		'SrEqual' => 'ShiftRightEqual',
		'Inc' => 'Increment',
		'Dec' => 'Decrement',
		'Class' => 'ClassKeyword', // "class" cannot be a class constant name
		'ClassC' => 'MagicClass',
		'TraitC' => 'MagicTrait',
		'MethodC' => 'MagicMethod',
		'FuncC' => 'MagicFunction',
		'PropertyC' => 'MagicProperty',
		'NsC' => 'MagicNamespace',
		'Line' => 'MagicLine',
		'File' => 'MagicFile',
		'Dir' => 'MagicDir',
	];

	preg_match_all('~^(T_\w+) = (\d+)$~m', $list, $matches, PREG_SET_ORDER);
	$kinds = ['EndOfFile' => 0];
	$hosts = [];
	$last = 0;
	foreach ($matches as [, $name, $number]) {
		$kind = str_replace('_', '', ucwords(strtolower(substr($name, 2)), '_'));
		$kind = $renames[$kind] ?? $kind;
		$kinds[$kind] = (int) $number;
		$hosts[$name] = $kind;
		$last = max($last, (int) $number);
	}

	foreach (['CloseTag', 'OpenTagWithEcho', 'HaltCompilerData'] as $kind) {
		$kinds[$kind] = ++$last;
	}

	$raw = [];
	foreach (['Whitespace', 'Comment', 'DocComment', 'OpenTag'] as $kind) {
		$raw[$kind] = ++$last;
	}

	$hosts += [
		'T_CLOSE_TAG' => 'CloseTag',
		'T_OPEN_TAG_WITH_ECHO' => 'OpenTagWithEcho',
		'T_WHITESPACE' => 'Whitespace',
		'T_COMMENT' => 'Comment',
		'T_DOC_COMMENT' => 'DocComment',
		'T_OPEN_TAG' => 'OpenTag',
	];

	$constants = fn(array $kinds) => implode(",\n", array_map(fn($kind, $number) => "\t\t$kind = $number", array_keys($kinds), $kinds));
	$hostConstants = implode("\n", array_map(fn($name, $kind) => "\t\t'$name' => self::$kind,", array_keys($hosts), $hosts));

	return str_replace("\r\n", "\n", <<<PHP
		<?php declare(strict_types=1);

		/**
		 * @generated by grammar/build.php from grammar/php.y, do not edit.
		 * Token kinds are derived from the grammar of nikic/php-parser (BSD-3-Clause, https://github.com/nikic/PHP-Parser).
		 */

		namespace PhpSyntax;


		/**
		 * Kinds of tokens; single-character tokens use the ordinal of the character as their kind.
		 */
		final class TokenKind
		{
			public const
		{$constants($kinds)};

			/** raw kinds between the tokenizer and trivia folding; they become trivia and never reach the parser */
			public const
		{$constants($raw)};

			/** PhpToken ids (T_* constant names) to kinds */
			public const HostConstants = [
		$hostConstants
			];
		}

		PHP);
}
