<?php declare(strict_types=1);

/**
 * Generates node classes from grammar/nodes.php; included by build.php.
 */

const NodesNamespace = 'PhpSyntax\Nodes';
const RootClasses = ['Node', 'Token'];
const DefaultParents = ['Expression' => 'ExpressionNode', 'Scalar' => 'ExpressionNode', 'Statement' => 'StatementNode', 'Type' => 'TypeNode', 'Member' => 'MemberNode'];


/**
 * @param array<string, array{description: string, slots: array<string, string>, extends?: string, implements?: list<string>, manual?: bool}> $schema
 */
function buildNodes(array $schema, string $dir): void
{
	$written = [];
	foreach ($schema as $class => $definition) {
		if ($definition['manual'] ?? false) {
			continue;
		}

		$file = $dir . '/' . strtr($class, '\\', '/') . '.php';
		@mkdir(dirname($file), 0o777, true);
		file_put_contents($file, renderNodeClass($class, $definition));
		$written[] = realpath($file);
	}

	$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS));
	foreach ($iterator as $file) {
		if (
			$file->getExtension() === 'php'
			&& !in_array(realpath($file->getPathname()), $written, strict: true)
			&& str_contains((string) file_get_contents($file->getPathname()), '@generated by grammar/build.php')
		) {
			unlink($file->getPathname());
			echo "Removed stale {$file->getPathname()}\n";
		}
	}
}


/**
 * @return array{nullable: bool, list: ?string, classes: list<string>}  list = NodeList|SeparatedNodeList, classes = item or slot types
 */
function parseSlotType(string $type): array
{
	$nullable = str_starts_with($type, '?');
	$type = ltrim($type, '?');
	$list = null;
	if (preg_match('~^(NodeList|SeparatedNodeList)<(.+)>$~', $type, $m)) {
		$list = $m[1];
		$type = $m[2];
	}

	return ['nullable' => $nullable, 'list' => $list, 'classes' => explode('|', $type)];
}


function resolveNodeClass(string $class): string
{
	return in_array($class, RootClasses, strict: true)
		? 'PhpSyntax\\' . $class
		: NodesNamespace . '\\' . $class;
}


/** @param array{description: string, slots: array<string, string>, extends?: string, implements?: list<string>} $definition */
function renderNodeClass(string $class, array $definition): string
{
	$namespace = NodesNamespace . (str_contains($class, '\\') ? '\\' . substr($class, 0, strrpos($class, '\\')) : '');
	$shortName = substr($class, strrpos($class, '\\') !== false ? strrpos($class, '\\') + 1 : 0);
	$parent = $definition['extends'] ?? DefaultParents[explode('\\', $class)[0]] ?? 'Node';
	$interfaces = $definition['implements'] ?? [];

	$imports = [];
	$use = function (string $class) use (&$imports, $namespace): string {
		$full = resolveNodeClass($class);
		$short = substr($full, strrpos($full, '\\') + 1);
		if (substr($full, 0, strrpos($full, '\\')) !== $namespace) {
			$imports[$full] = true;
		}

		return $short;
	};
	$use('Node');
	$use('Token');

	$slots = [];
	foreach ($definition['slots'] as $name => $type) {
		$info = parseSlotType($type);
		$shorts = array_map($use, $info['classes']);
		$native = $info['list'] ? $use($info['list']) : implode('|', $shorts);
		$slots[$name] = [
			'nullable' => $info['nullable'],
			'list' => $info['list'],
			'native' => ($info['nullable'] ? (count($shorts) > 1 && !$info['list'] ? '' : '?') : '') . $native . ($info['nullable'] && count($shorts) > 1 && !$info['list'] ? '|null' : ''),
			'doc' => $info['list'] ? $native . '<' . implode('|', $shorts) . '>' : null,
			'check' => $info['list']
				? '$new instanceof ' . $native
				: implode(' || ', array_map(fn($s) => '$new instanceof ' . $s, $shorts)),
			'shorts' => $shorts,
		];
	}

	$parentShort = $use($parent);
	$interfaceShorts = array_map($use, $interfaces);
	$traitShorts = array_map($use, $definition['traits'] ?? []);
	ksort($imports);

	$lines = [];
	$lines[] = '<?php declare(strict_types=1);';
	$lines[] = '';
	$lines[] = '/**';
	$lines[] = ' * @generated by grammar/build.php from grammar/nodes.php, do not edit.';
	$lines[] = ' */';
	$lines[] = '';
	$lines[] = "namespace $namespace;";
	$lines[] = '';
	foreach (array_keys($imports) as $import) {
		$lines[] = "use $import;";
	}

	$lines[] = '';
	$lines[] = '';
	$lines[] = '/**';
	$lines[] = ' * ' . $definition['description'];
	$lines[] = ' */';
	$lines[] = "final class $shortName extends $parentShort" . ($interfaceShorts ? ' implements ' . implode(', ', $interfaceShorts) : '');
	$lines[] = '{';
	foreach ($traitShorts as $trait) {
		$lines[] = "\tuse $trait;";
	}

	if ($traitShorts) {
		$lines[] = '';
		$lines[] = '';
	}

	// constructor
	$docs = [];
	foreach ($slots as $name => $slot) {
		if ($slot['doc']) {
			$docs[] = ' * @param ' . ($slot['nullable'] ? '?' : '') . "{$slot['doc']} \$$name";
		}
	}

	$lines[] = "\t/**";
	foreach ($docs as $doc) {
		$lines[] = "\t" . $doc;
	}

	$lines[] = "\t * @internal nodes are created by the parser";
	$lines[] = "\t */";
	if ($slots) {
		$lines[] = "\tpublic function __construct(";
		foreach ($slots as $name => $slot) {
			$lines[] = "\t\tpublic {$slot['native']} \$$name,";
		}

		$lines[] = "\t) {";
		$lines[] = "\t}";
	} else {
		$lines[] = "\tpublic function __construct()";
		$lines[] = "\t{";
		$lines[] = "\t}";
	}

	// children
	$lines[] = '';
	$lines[] = '';
	$lines[] = "\tpublic function getChildren(): array";
	$lines[] = "\t{";
	$nullable = array_filter($slots, fn(array $slot) => $slot['nullable']);
	if (!$nullable) {
		$lines[] = "\t\treturn [" . implode(', ', array_map(fn(string $name) => "\$this->$name", array_keys($slots))) . '];';
	} else {
		$lines[] = "\t\t\$children = [];";
		foreach ($slots as $name => $slot) {
			if ($slot['nullable']) {
				$lines[] = "\t\tif (\$this->$name) {";
				$lines[] = "\t\t\t\$children[] = \$this->$name;";
				$lines[] = "\t\t}";
			} else {
				$lines[] = "\t\t\$children[] = \$this->$name;";
			}
		}

		$lines[] = '';
		$lines[] = "\t\treturn \$children;";
	}

	$lines[] = "\t}";

	// replaceChild
	$lines[] = '';
	$lines[] = '';
	$lines[] = "\tpublic function replaceChild(Node|Token \$old, Node|Token \$new): void";
	$lines[] = "\t{";
	$first = true;
	foreach ($slots as $name => $slot) {
		$setter = 'set' . ucfirst($name);
		$lines[] = "\t\t" . ($first ? 'if' : '} elseif') . " (\$old === \$this->$name) {";
		if ($slot['list']) {
			$lines[] = "\t\t\tif (!{$slot['check']}) {";
			$lines[] = "\t\t\t\tthrow self::describeSlotMismatch('$name', \$new);";
			$lines[] = "\t\t\t}";
			$lines[] = '';
			$lines[] = "\t\t\t/** @var {$slot['doc']} \$new  the item type is erased at runtime */";
			$lines[] = "\t\t\t\$this->$setter(\$new);";
		} else {
			$lines[] = "\t\t\t\$this->$setter({$slot['check']} ? \$new : throw self::describeSlotMismatch('$name', \$new));";
		}

		$first = false;
	}

	$lines[] = "\t\t" . ($first ? '' : '} else {');
	$lines[] = ($first ? "\t\t" : "\t\t\t") . 'throw self::describeChildMismatch($old);';
	if (!$first) {
		$lines[] = "\t\t}";
	}

	$lines[] = "\t}";

	// setters
	foreach ($slots as $name => $slot) {
		$setter = 'set' . ucfirst($name);
		$lines[] = '';
		$lines[] = '';
		if ($slot['doc']) {
			$lines[] = "\t/** @param " . ($slot['nullable'] ? '?' : '') . "{$slot['doc']} \$$name */";
		}

		$lines[] = "\tpublic function $setter({$slot['native']} \$$name): void";
		$lines[] = "\t{";
		if ($slot['nullable']) {
			$lines[] = "\t\tif (\$$name) {";
			$lines[] = "\t\t\t\$this->adopt(\$$name);";
			$lines[] = "\t\t}";
			$lines[] = '';
		} else {
			$lines[] = "\t\t\$this->adopt(\$$name);";
		}

		$lines[] = "\t\t\$this->release(\$this->$name);";
		$lines[] = "\t\t\$this->$name = \$$name;";
		$lines[] = "\t\t\$this->structureChanged();";
		$lines[] = "\t}";
	}

	$lines[] = '}';
	$lines[] = '';
	return implode("\n", $lines);
}
