<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Type;

use PhpSyntax\Node;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Intersection type A&B, parenthesized inside a union.
 */
final class IntersectionTypeNode extends TypeNode
{
	/**
	 * @param SeparatedNodeList<TypeNode> $types
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?Token $openParen,
		public SeparatedNodeList $types,
		public ?Token $closeParen,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->openParen) {
			$children[] = $this->openParen;
		}
		$children[] = $this->types;
		if ($this->closeParen) {
			$children[] = $this->closeParen;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->types) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('types', $new);
			}

			/** @var SeparatedNodeList<TypeNode> $new  the item type is erased at runtime */
			$this->setTypes($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenParen(?Token $openParen): void
	{
		if ($openParen) {
			$this->adopt($openParen);
		}

		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<TypeNode> $types */
	public function setTypes(SeparatedNodeList $types): void
	{
		$this->adopt($types);
		$this->release($this->types);
		$this->types = $types;
		$this->structureChanged();
	}


	public function setCloseParen(?Token $closeParen): void
	{
		if ($closeParen) {
			$this->adopt($closeParen);
		}

		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}
}
