<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Type;

use PhpSyntax\Node;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Nullable type: ?T.
 */
final class NullableTypeNode extends TypeNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $question,
		public TypeNode $type,
	) {
	}


	public function getChildren(): array
	{
		return [$this->question, $this->type];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->question) {
			$this->setQuestion($new instanceof Token ? $new : throw self::describeSlotMismatch('question', $new));
		} elseif ($old === $this->type) {
			$this->setType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('type', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setQuestion(Token $question): void
	{
		$this->adopt($question);
		$this->release($this->question);
		$this->question = $question;
		$this->structureChanged();
	}


	public function setType(TypeNode $type): void
	{
		$this->adopt($type);
		$this->release($this->type);
		$this->type = $type;
		$this->structureChanged();
	}
}
