<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Type;

use PhpSyntax\Node;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Union type A|B; a member may be a parenthesized intersection (DNF).
 */
final class UnionTypeNode extends TypeNode
{
	/**
	 * @param SeparatedNodeList<TypeNode> $types
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public SeparatedNodeList $types,
	) {
	}


	public function getChildren(): array
	{
		return [$this->types];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->types) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('types', $new);
			}

			/** @var SeparatedNodeList<TypeNode> $new  the item type is erased at runtime */
			$this->setTypes($new);
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param SeparatedNodeList<TypeNode> $types */
	public function setTypes(SeparatedNodeList $types): void
	{
		$this->adopt($types);
		$this->release($this->types);
		$this->types = $types;
		$this->structureChanged();
	}
}
