<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Array or string offset access: $a[$i], $a[].
 */
final class ArrayDimFetchNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $var,
		public Token $openBracket,
		public ?ExpressionNode $dim,
		public Token $closeBracket,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->var;
		$children[] = $this->openBracket;
		if ($this->dim) {
			$children[] = $this->dim;
		}
		$children[] = $this->closeBracket;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->var) {
			$this->setVar($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('var', $new));
		} elseif ($old === $this->openBracket) {
			$this->setOpenBracket($new instanceof Token ? $new : throw self::describeSlotMismatch('openBracket', $new));
		} elseif ($old === $this->dim) {
			$this->setDim($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('dim', $new));
		} elseif ($old === $this->closeBracket) {
			$this->setCloseBracket($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBracket', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setVar(ExpressionNode $var): void
	{
		$this->adopt($var);
		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}


	public function setOpenBracket(Token $openBracket): void
	{
		$this->adopt($openBracket);
		$this->release($this->openBracket);
		$this->openBracket = $openBracket;
		$this->structureChanged();
	}


	public function setDim(?ExpressionNode $dim): void
	{
		if ($dim) {
			$this->adopt($dim);
		}

		$this->release($this->dim);
		$this->dim = $dim;
		$this->structureChanged();
	}


	public function setCloseBracket(Token $closeBracket): void
	{
		$this->adopt($closeBracket);
		$this->release($this->closeBracket);
		$this->closeBracket = $closeBracket;
		$this->structureChanged();
	}
}
