<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ArrayItemNode;
use PhpSyntax\Nodes\EmptyArrayItemNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * Array literal in either syntax: [...] or array(...); on the left of an assignment it destructures.
 */
final class ArrayNode extends ExpressionNode
{
	/**
	 * @param SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?Token $arrayKeyword,
		public Token $openDelimiter,
		public SeparatedNodeList $items,
		public Token $closeDelimiter,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->arrayKeyword) {
			$children[] = $this->arrayKeyword;
		}
		$children[] = $this->openDelimiter;
		$children[] = $this->items;
		$children[] = $this->closeDelimiter;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->arrayKeyword) {
			$this->setArrayKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('arrayKeyword', $new));
		} elseif ($old === $this->openDelimiter) {
			$this->setOpenDelimiter($new instanceof Token ? $new : throw self::describeSlotMismatch('openDelimiter', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->closeDelimiter) {
			$this->setCloseDelimiter($new instanceof Token ? $new : throw self::describeSlotMismatch('closeDelimiter', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setArrayKeyword(?Token $arrayKeyword): void
	{
		if ($arrayKeyword) {
			$this->adopt($arrayKeyword);
		}

		$this->release($this->arrayKeyword);
		$this->arrayKeyword = $arrayKeyword;
		$this->structureChanged();
	}


	public function setOpenDelimiter(Token $openDelimiter): void
	{
		$this->adopt($openDelimiter);
		$this->release($this->openDelimiter);
		$this->openDelimiter = $openDelimiter;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setCloseDelimiter(Token $closeDelimiter): void
	{
		$this->adopt($closeDelimiter);
		$this->release($this->closeDelimiter);
		$this->closeDelimiter = $closeDelimiter;
		$this->structureChanged();
	}
}
