<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AttributeGroupNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\ParameterNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Nodes\TypeNode;
use PhpSyntax\Token;


/**
 * Arrow function fn(...) => expr, optionally static.
 */
final class ArrowFunctionNode extends ExpressionNode
{
	/**
	 * @param NodeList<AttributeGroupNode> $attributes
	 * @param SeparatedNodeList<ParameterNode> $params
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NodeList $attributes,
		public ?Token $staticKeyword,
		public Token $fnKeyword,
		public ?Token $byRef,
		public Token $openParen,
		public SeparatedNodeList $params,
		public Token $closeParen,
		public ?Token $colon,
		public ?TypeNode $returnType,
		public Token $doubleArrow,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->attributes;
		if ($this->staticKeyword) {
			$children[] = $this->staticKeyword;
		}
		$children[] = $this->fnKeyword;
		if ($this->byRef) {
			$children[] = $this->byRef;
		}
		$children[] = $this->openParen;
		$children[] = $this->params;
		$children[] = $this->closeParen;
		if ($this->colon) {
			$children[] = $this->colon;
		}
		if ($this->returnType) {
			$children[] = $this->returnType;
		}
		$children[] = $this->doubleArrow;
		$children[] = $this->expr;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->attributes) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('attributes', $new);
			}

			/** @var NodeList<AttributeGroupNode> $new  the item type is erased at runtime */
			$this->setAttributes($new);
		} elseif ($old === $this->staticKeyword) {
			$this->setStaticKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('staticKeyword', $new));
		} elseif ($old === $this->fnKeyword) {
			$this->setFnKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('fnKeyword', $new));
		} elseif ($old === $this->byRef) {
			$this->setByRef($new instanceof Token ? $new : throw self::describeSlotMismatch('byRef', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->params) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('params', $new);
			}

			/** @var SeparatedNodeList<ParameterNode> $new  the item type is erased at runtime */
			$this->setParams($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->returnType) {
			$this->setReturnType($new instanceof TypeNode ? $new : throw self::describeSlotMismatch('returnType', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	/** @param NodeList<AttributeGroupNode> $attributes */
	public function setAttributes(NodeList $attributes): void
	{
		$this->adopt($attributes);
		$this->release($this->attributes);
		$this->attributes = $attributes;
		$this->structureChanged();
	}


	public function setStaticKeyword(?Token $staticKeyword): void
	{
		if ($staticKeyword) {
			$this->adopt($staticKeyword);
		}

		$this->release($this->staticKeyword);
		$this->staticKeyword = $staticKeyword;
		$this->structureChanged();
	}


	public function setFnKeyword(Token $fnKeyword): void
	{
		$this->adopt($fnKeyword);
		$this->release($this->fnKeyword);
		$this->fnKeyword = $fnKeyword;
		$this->structureChanged();
	}


	public function setByRef(?Token $byRef): void
	{
		if ($byRef) {
			$this->adopt($byRef);
		}

		$this->release($this->byRef);
		$this->byRef = $byRef;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ParameterNode> $params */
	public function setParams(SeparatedNodeList $params): void
	{
		$this->adopt($params);
		$this->release($this->params);
		$this->params = $params;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setColon(?Token $colon): void
	{
		if ($colon) {
			$this->adopt($colon);
		}

		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setReturnType(?TypeNode $returnType): void
	{
		if ($returnType) {
			$this->adopt($returnType);
		}

		$this->release($this->returnType);
		$this->returnType = $returnType;
		$this->structureChanged();
	}


	public function setDoubleArrow(Token $doubleArrow): void
	{
		$this->adopt($doubleArrow);
		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
