<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Assignment by reference: $a = &$b.
 */
final class AssignRefNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $var,
		public Token $equals,
		public Token $ampersand,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->var, $this->equals, $this->ampersand, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->var) {
			$this->setVar($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('var', $new));
		} elseif ($old === $this->equals) {
			$this->setEquals($new instanceof Token ? $new : throw self::describeSlotMismatch('equals', $new));
		} elseif ($old === $this->ampersand) {
			$this->setAmpersand($new instanceof Token ? $new : throw self::describeSlotMismatch('ampersand', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setVar(ExpressionNode $var): void
	{
		$this->adopt($var);
		$this->release($this->var);
		$this->var = $var;
		$this->structureChanged();
	}


	public function setEquals(Token $equals): void
	{
		$this->adopt($equals);
		$this->release($this->equals);
		$this->equals = $equals;
		$this->structureChanged();
	}


	public function setAmpersand(Token $ampersand): void
	{
		$this->adopt($ampersand);
		$this->release($this->ampersand);
		$this->ampersand = $ampersand;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
