<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Binary operation; the operator token tells which (arithmetic, comparison, logical, bitwise, concatenation, coalesce, pipe).
 */
final class BinaryNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $left,
		public Token $operator,
		public ExpressionNode $right,
	) {
	}


	public function getChildren(): array
	{
		return [$this->left, $this->operator, $this->right];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->left) {
			$this->setLeft($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('left', $new));
		} elseif ($old === $this->operator) {
			$this->setOperator($new instanceof Token ? $new : throw self::describeSlotMismatch('operator', $new));
		} elseif ($old === $this->right) {
			$this->setRight($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('right', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setLeft(ExpressionNode $left): void
	{
		$this->adopt($left);
		$this->release($this->left);
		$this->left = $left;
		$this->structureChanged();
	}


	public function setOperator(Token $operator): void
	{
		$this->adopt($operator);
		$this->release($this->operator);
		$this->operator = $operator;
		$this->structureChanged();
	}


	public function setRight(ExpressionNode $right): void
	{
		$this->adopt($right);
		$this->release($this->right);
		$this->right = $right;
		$this->structureChanged();
	}
}
