<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Type cast; the cast token keeps its spelling including inner whitespace: ( int ).
 */
final class CastNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $cast,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->cast, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->cast) {
			$this->setCast($new instanceof Token ? $new : throw self::describeSlotMismatch('cast', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setCast(Token $cast): void
	{
		$this->adopt($cast);
		$this->release($this->cast);
		$this->cast = $cast;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
