<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Class constant access: A::B, A::class, A::{expr}.
 */
final class ClassConstantFetchNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode|ExpressionNode $class,
		public Token $doubleColon,
		public ?Token $openBrace,
		public IdentifierNode|ExpressionNode $name,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->class;
		$children[] = $this->doubleColon;
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		$children[] = $this->name;
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->class) {
			$this->setClass($new instanceof NameNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('class', $new));
		} elseif ($old === $this->doubleColon) {
			$this->setDoubleColon($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleColon', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setClass(NameNode|ExpressionNode $class): void
	{
		$this->adopt($class);
		$this->release($this->class);
		$this->class = $class;
		$this->structureChanged();
	}


	public function setDoubleColon(Token $doubleColon): void
	{
		$this->adopt($doubleColon);
		$this->release($this->doubleColon);
		$this->doubleColon = $doubleColon;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	public function setName(IdentifierNode|ExpressionNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
