<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * clone expression; clone(...) with arguments is a function call.
 */
final class CloneNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $cloneKeyword,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->cloneKeyword, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->cloneKeyword) {
			$this->setCloneKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('cloneKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setCloneKeyword(Token $cloneKeyword): void
	{
		$this->adopt($cloneKeyword);
		$this->release($this->cloneKeyword);
		$this->cloneKeyword = $cloneKeyword;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
