<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Constant access by name: FOO, \Foo\BAR, true.
 */
final class ConstantFetchNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode $name,
	) {
	}


	public function getChildren(): array
	{
		return [$this->name];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof NameNode ? $new : throw self::describeSlotMismatch('name', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(NameNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}
}
