<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ArgumentListNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * exit or die with optional arguments.
 */
final class ExitNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $exitKeyword,
		public ?ArgumentListNode $args,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->exitKeyword;
		if ($this->args) {
			$children[] = $this->args;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->exitKeyword) {
			$this->setExitKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('exitKeyword', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setExitKeyword(Token $exitKeyword): void
	{
		$this->adopt($exitKeyword);
		$this->release($this->exitKeyword);
		$this->exitKeyword = $exitKeyword;
		$this->structureChanged();
	}


	public function setArgs(?ArgumentListNode $args): void
	{
		if ($args) {
			$this->adopt($args);
		}

		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}
}
