<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ArgumentListNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Function call by name or on an expression.
 */
final class FunctionCallNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode|ExpressionNode $name,
		public ArgumentListNode $args,
	) {
	}


	public function getChildren(): array
	{
		return [$this->name, $this->args];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->name) {
			$this->setName($new instanceof NameNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setName(NameNode|ExpressionNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setArgs(ArgumentListNode $args): void
	{
		$this->adopt($args);
		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}
}
