<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * include, include_once, require or require_once; the keyword token tells which.
 */
final class IncludeNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $includeKeyword,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->includeKeyword, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->includeKeyword) {
			$this->setIncludeKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('includeKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setIncludeKeyword(Token $includeKeyword): void
	{
		$this->adopt($includeKeyword);
		$this->release($this->includeKeyword);
		$this->includeKeyword = $includeKeyword;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
