<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * instanceof check against a name or a dynamic class.
 */
final class InstanceofNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $expr,
		public Token $instanceofKeyword,
		public NameNode|ExpressionNode $class,
	) {
	}


	public function getChildren(): array
	{
		return [$this->expr, $this->instanceofKeyword, $this->class];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} elseif ($old === $this->instanceofKeyword) {
			$this->setInstanceofKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('instanceofKeyword', $new));
		} elseif ($old === $this->class) {
			$this->setClass($new instanceof NameNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('class', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}


	public function setInstanceofKeyword(Token $instanceofKeyword): void
	{
		$this->adopt($instanceofKeyword);
		$this->release($this->instanceofKeyword);
		$this->instanceofKeyword = $instanceofKeyword;
		$this->structureChanged();
	}


	public function setClass(NameNode|ExpressionNode $class): void
	{
		$this->adopt($class);
		$this->release($this->class);
		$this->class = $class;
		$this->structureChanged();
	}
}
