<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * isset(...) with one or more variables.
 */
final class IssetNode extends ExpressionNode
{
	/**
	 * @param SeparatedNodeList<ExpressionNode> $vars
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $issetKeyword,
		public Token $openParen,
		public SeparatedNodeList $vars,
		public Token $closeParen,
	) {
	}


	public function getChildren(): array
	{
		return [$this->issetKeyword, $this->openParen, $this->vars, $this->closeParen];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->issetKeyword) {
			$this->setIssetKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('issetKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->vars) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('vars', $new);
			}

			/** @var SeparatedNodeList<ExpressionNode> $new  the item type is erased at runtime */
			$this->setVars($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setIssetKeyword(Token $issetKeyword): void
	{
		$this->adopt($issetKeyword);
		$this->release($this->issetKeyword);
		$this->issetKeyword = $issetKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ExpressionNode> $vars */
	public function setVars(SeparatedNodeList $vars): void
	{
		$this->adopt($vars);
		$this->release($this->vars);
		$this->vars = $vars;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}
}
