<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ArrayItemNode;
use PhpSyntax\Nodes\EmptyArrayItemNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * Destructuring with list(...).
 */
final class ListNode extends ExpressionNode
{
	/**
	 * @param SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $items
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $listKeyword,
		public Token $openParen,
		public SeparatedNodeList $items,
		public Token $closeParen,
	) {
	}


	public function getChildren(): array
	{
		return [$this->listKeyword, $this->openParen, $this->items, $this->closeParen];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->listKeyword) {
			$this->setListKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('listKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->items) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('items', $new);
			}

			/** @var SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $new  the item type is erased at runtime */
			$this->setItems($new);
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setListKeyword(Token $listKeyword): void
	{
		$this->adopt($listKeyword);
		$this->release($this->listKeyword);
		$this->listKeyword = $listKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<ArrayItemNode|EmptyArrayItemNode> $items */
	public function setItems(SeparatedNodeList $items): void
	{
		$this->adopt($items);
		$this->release($this->items);
		$this->items = $items;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}
}
