<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\MatchArmNode;
use PhpSyntax\Nodes\SeparatedNodeList;
use PhpSyntax\Token;


/**
 * match expression.
 */
final class MatchNode extends ExpressionNode
{
	/**
	 * @param SeparatedNodeList<MatchArmNode> $arms
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $matchKeyword,
		public Token $openParen,
		public ExpressionNode $cond,
		public Token $closeParen,
		public Token $openBrace,
		public SeparatedNodeList $arms,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		return [$this->matchKeyword, $this->openParen, $this->cond, $this->closeParen, $this->openBrace, $this->arms, $this->closeBrace];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->matchKeyword) {
			$this->setMatchKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('matchKeyword', $new));
		} elseif ($old === $this->openParen) {
			$this->setOpenParen($new instanceof Token ? $new : throw self::describeSlotMismatch('openParen', $new));
		} elseif ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->closeParen) {
			$this->setCloseParen($new instanceof Token ? $new : throw self::describeSlotMismatch('closeParen', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->arms) {
			if (!$new instanceof SeparatedNodeList) {
				throw self::describeSlotMismatch('arms', $new);
			}

			/** @var SeparatedNodeList<MatchArmNode> $new  the item type is erased at runtime */
			$this->setArms($new);
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setMatchKeyword(Token $matchKeyword): void
	{
		$this->adopt($matchKeyword);
		$this->release($this->matchKeyword);
		$this->matchKeyword = $matchKeyword;
		$this->structureChanged();
	}


	public function setOpenParen(Token $openParen): void
	{
		$this->adopt($openParen);
		$this->release($this->openParen);
		$this->openParen = $openParen;
		$this->structureChanged();
	}


	public function setCond(ExpressionNode $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setCloseParen(Token $closeParen): void
	{
		$this->adopt($closeParen);
		$this->release($this->closeParen);
		$this->closeParen = $closeParen;
		$this->structureChanged();
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	/** @param SeparatedNodeList<MatchArmNode> $arms */
	public function setArms(SeparatedNodeList $arms): void
	{
		$this->adopt($arms);
		$this->release($this->arms);
		$this->arms = $arms;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
