<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ArgumentListNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\IdentifierNode;
use PhpSyntax\Token;


/**
 * Method call with -> or ?->.
 */
final class MethodCallNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $object,
		public Token $operator,
		public ?Token $openBrace,
		public IdentifierNode|ExpressionNode $name,
		public ?Token $closeBrace,
		public ArgumentListNode $args,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->object;
		$children[] = $this->operator;
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		$children[] = $this->name;
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}
		$children[] = $this->args;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->object) {
			$this->setObject($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('object', $new));
		} elseif ($old === $this->operator) {
			$this->setOperator($new instanceof Token ? $new : throw self::describeSlotMismatch('operator', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof IdentifierNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setObject(ExpressionNode $object): void
	{
		$this->adopt($object);
		$this->release($this->object);
		$this->object = $object;
		$this->structureChanged();
	}


	public function setOperator(Token $operator): void
	{
		$this->adopt($operator);
		$this->release($this->operator);
		$this->operator = $operator;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	public function setName(IdentifierNode|ExpressionNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}


	public function setArgs(ArgumentListNode $args): void
	{
		$this->adopt($args);
		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}
}
