<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\AnonymousClassNode;
use PhpSyntax\Nodes\ArgumentListNode;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Instantiation of a named, dynamic or anonymous class.
 */
final class NewNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $newKeyword,
		public NameNode|ExpressionNode|AnonymousClassNode $class,
		public ?ArgumentListNode $args,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->newKeyword;
		$children[] = $this->class;
		if ($this->args) {
			$children[] = $this->args;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->newKeyword) {
			$this->setNewKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('newKeyword', $new));
		} elseif ($old === $this->class) {
			$this->setClass($new instanceof NameNode || $new instanceof ExpressionNode || $new instanceof AnonymousClassNode ? $new : throw self::describeSlotMismatch('class', $new));
		} elseif ($old === $this->args) {
			$this->setArgs($new instanceof ArgumentListNode ? $new : throw self::describeSlotMismatch('args', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setNewKeyword(Token $newKeyword): void
	{
		$this->adopt($newKeyword);
		$this->release($this->newKeyword);
		$this->newKeyword = $newKeyword;
		$this->structureChanged();
	}


	public function setClass(NameNode|ExpressionNode|AnonymousClassNode $class): void
	{
		$this->adopt($class);
		$this->release($this->class);
		$this->class = $class;
		$this->structureChanged();
	}


	public function setArgs(?ArgumentListNode $args): void
	{
		if ($args) {
			$this->adopt($args);
		}

		$this->release($this->args);
		$this->args = $args;
		$this->structureChanged();
	}
}
