<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * print expression.
 */
final class PrintNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $printKeyword,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->printKeyword, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->printKeyword) {
			$this->setPrintKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('printKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setPrintKeyword(Token $printKeyword): void
	{
		$this->adopt($printKeyword);
		$this->release($this->printKeyword);
		$this->printKeyword = $printKeyword;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
