<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Nodes\Scalar\InterpolatedStringPartNode;
use PhpSyntax\Nodes\Scalar\InterpolationNode;
use PhpSyntax\Token;


/**
 * Command in backticks with interpolation.
 */
final class ShellExecNode extends ExpressionNode
{
	/**
	 * @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openBacktick,
		public NodeList $parts,
		public Token $closeBacktick,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openBacktick, $this->parts, $this->closeBacktick];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openBacktick) {
			$this->setOpenBacktick($new instanceof Token ? $new : throw self::describeSlotMismatch('openBacktick', $new));
		} elseif ($old === $this->parts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('parts', $new);
			}

			/** @var NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $new  the item type is erased at runtime */
			$this->setParts($new);
		} elseif ($old === $this->closeBacktick) {
			$this->setCloseBacktick($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBacktick', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenBacktick(Token $openBacktick): void
	{
		$this->adopt($openBacktick);
		$this->release($this->openBacktick);
		$this->openBacktick = $openBacktick;
		$this->structureChanged();
	}


	/** @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts */
	public function setParts(NodeList $parts): void
	{
		$this->adopt($parts);
		$this->release($this->parts);
		$this->parts = $parts;
		$this->structureChanged();
	}


	public function setCloseBacktick(Token $closeBacktick): void
	{
		$this->adopt($closeBacktick);
		$this->release($this->closeBacktick);
		$this->closeBacktick = $closeBacktick;
		$this->structureChanged();
	}
}
