<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NameNode;
use PhpSyntax\Token;


/**
 * Static property access: A::$b.
 */
final class StaticPropertyFetchNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public NameNode|ExpressionNode $class,
		public Token $doubleColon,
		public VariableNode $name,
	) {
	}


	public function getChildren(): array
	{
		return [$this->class, $this->doubleColon, $this->name];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->class) {
			$this->setClass($new instanceof NameNode || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('class', $new));
		} elseif ($old === $this->doubleColon) {
			$this->setDoubleColon($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleColon', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof VariableNode ? $new : throw self::describeSlotMismatch('name', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setClass(NameNode|ExpressionNode $class): void
	{
		$this->adopt($class);
		$this->release($this->class);
		$this->class = $class;
		$this->structureChanged();
	}


	public function setDoubleColon(Token $doubleColon): void
	{
		$this->adopt($doubleColon);
		$this->release($this->doubleColon);
		$this->doubleColon = $doubleColon;
		$this->structureChanged();
	}


	public function setName(VariableNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}
}
