<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Ternary conditional ($cond ? $if : $else) or the elvis form ($cond ?: $else).
 */
final class TernaryNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ExpressionNode $cond,
		public Token $question,
		public ?ExpressionNode $if,
		public Token $colon,
		public ExpressionNode $else,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->cond;
		$children[] = $this->question;
		if ($this->if) {
			$children[] = $this->if;
		}
		$children[] = $this->colon;
		$children[] = $this->else;

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->cond) {
			$this->setCond($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('cond', $new));
		} elseif ($old === $this->question) {
			$this->setQuestion($new instanceof Token ? $new : throw self::describeSlotMismatch('question', $new));
		} elseif ($old === $this->if) {
			$this->setIf($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('if', $new));
		} elseif ($old === $this->colon) {
			$this->setColon($new instanceof Token ? $new : throw self::describeSlotMismatch('colon', $new));
		} elseif ($old === $this->else) {
			$this->setElse($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('else', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setCond(ExpressionNode $cond): void
	{
		$this->adopt($cond);
		$this->release($this->cond);
		$this->cond = $cond;
		$this->structureChanged();
	}


	public function setQuestion(Token $question): void
	{
		$this->adopt($question);
		$this->release($this->question);
		$this->question = $question;
		$this->structureChanged();
	}


	public function setIf(?ExpressionNode $if): void
	{
		if ($if) {
			$this->adopt($if);
		}

		$this->release($this->if);
		$this->if = $if;
		$this->structureChanged();
	}


	public function setColon(Token $colon): void
	{
		$this->adopt($colon);
		$this->release($this->colon);
		$this->colon = $colon;
		$this->structureChanged();
	}


	public function setElse(ExpressionNode $else): void
	{
		$this->adopt($else);
		$this->release($this->else);
		$this->else = $else;
		$this->structureChanged();
	}
}
