<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * throw expression.
 */
final class ThrowNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $throwKeyword,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->throwKeyword, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->throwKeyword) {
			$this->setThrowKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('throwKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setThrowKeyword(Token $throwKeyword): void
	{
		$this->adopt($throwKeyword);
		$this->release($this->throwKeyword);
		$this->throwKeyword = $throwKeyword;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
