<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Prefix operation: +, -, !, ~, @, ++, --.
 */
final class UnaryNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $operator,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->operator, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->operator) {
			$this->setOperator($new instanceof Token ? $new : throw self::describeSlotMismatch('operator', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOperator(Token $operator): void
	{
		$this->adopt($operator);
		$this->release($this->operator);
		$this->operator = $operator;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
