<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Variable: $a, $$a, ${expr}; inside a string also a bare name in ${name}.
 */
final class VariableNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public ?Token $dollar,
		public ?Token $openBrace,
		public Token|ExpressionNode $name,
		public ?Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		if ($this->dollar) {
			$children[] = $this->dollar;
		}
		if ($this->openBrace) {
			$children[] = $this->openBrace;
		}
		$children[] = $this->name;
		if ($this->closeBrace) {
			$children[] = $this->closeBrace;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->dollar) {
			$this->setDollar($new instanceof Token ? $new : throw self::describeSlotMismatch('dollar', $new));
		} elseif ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->name) {
			$this->setName($new instanceof Token || $new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('name', $new));
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setDollar(?Token $dollar): void
	{
		if ($dollar) {
			$this->adopt($dollar);
		}

		$this->release($this->dollar);
		$this->dollar = $dollar;
		$this->structureChanged();
	}


	public function setOpenBrace(?Token $openBrace): void
	{
		if ($openBrace) {
			$this->adopt($openBrace);
		}

		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	public function setName(Token|ExpressionNode $name): void
	{
		$this->adopt($name);
		$this->release($this->name);
		$this->name = $name;
		$this->structureChanged();
	}


	public function setCloseBrace(?Token $closeBrace): void
	{
		if ($closeBrace) {
			$this->adopt($closeBrace);
		}

		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
