<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * yield from expression.
 */
final class YieldFromNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $yieldFromKeyword,
		public ExpressionNode $expr,
	) {
	}


	public function getChildren(): array
	{
		return [$this->yieldFromKeyword, $this->expr];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->yieldFromKeyword) {
			$this->setYieldFromKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('yieldFromKeyword', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setYieldFromKeyword(Token $yieldFromKeyword): void
	{
		$this->adopt($yieldFromKeyword);
		$this->release($this->yieldFromKeyword);
		$this->yieldFromKeyword = $yieldFromKeyword;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}
}
