<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Expression;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * yield, yield $value or yield $key => $value.
 */
final class YieldNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $yieldKeyword,
		public ?ExpressionNode $key,
		public ?Token $doubleArrow,
		public ?ExpressionNode $value,
	) {
	}


	public function getChildren(): array
	{
		$children = [];
		$children[] = $this->yieldKeyword;
		if ($this->key) {
			$children[] = $this->key;
		}
		if ($this->doubleArrow) {
			$children[] = $this->doubleArrow;
		}
		if ($this->value) {
			$children[] = $this->value;
		}

		return $children;
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->yieldKeyword) {
			$this->setYieldKeyword($new instanceof Token ? $new : throw self::describeSlotMismatch('yieldKeyword', $new));
		} elseif ($old === $this->key) {
			$this->setKey($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('key', $new));
		} elseif ($old === $this->doubleArrow) {
			$this->setDoubleArrow($new instanceof Token ? $new : throw self::describeSlotMismatch('doubleArrow', $new));
		} elseif ($old === $this->value) {
			$this->setValue($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('value', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setYieldKeyword(Token $yieldKeyword): void
	{
		$this->adopt($yieldKeyword);
		$this->release($this->yieldKeyword);
		$this->yieldKeyword = $yieldKeyword;
		$this->structureChanged();
	}


	public function setKey(?ExpressionNode $key): void
	{
		if ($key) {
			$this->adopt($key);
		}

		$this->release($this->key);
		$this->key = $key;
		$this->structureChanged();
	}


	public function setDoubleArrow(?Token $doubleArrow): void
	{
		if ($doubleArrow) {
			$this->adopt($doubleArrow);
		}

		$this->release($this->doubleArrow);
		$this->doubleArrow = $doubleArrow;
		$this->structureChanged();
	}


	public function setValue(?ExpressionNode $value): void
	{
		if ($value) {
			$this->adopt($value);
		}

		$this->release($this->value);
		$this->value = $value;
		$this->structureChanged();
	}
}
