<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Scalar;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Token;


/**
 * Heredoc or nowdoc; the closing delimiter keeps its indentation, the parts keep theirs.
 */
final class HeredocNode extends ExpressionNode
{
	/**
	 * @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openDelimiter,
		public NodeList $parts,
		public Token $closeDelimiter,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openDelimiter, $this->parts, $this->closeDelimiter];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openDelimiter) {
			$this->setOpenDelimiter($new instanceof Token ? $new : throw self::describeSlotMismatch('openDelimiter', $new));
		} elseif ($old === $this->parts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('parts', $new);
			}

			/** @var NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $new  the item type is erased at runtime */
			$this->setParts($new);
		} elseif ($old === $this->closeDelimiter) {
			$this->setCloseDelimiter($new instanceof Token ? $new : throw self::describeSlotMismatch('closeDelimiter', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenDelimiter(Token $openDelimiter): void
	{
		$this->adopt($openDelimiter);
		$this->release($this->openDelimiter);
		$this->openDelimiter = $openDelimiter;
		$this->structureChanged();
	}


	/** @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts */
	public function setParts(NodeList $parts): void
	{
		$this->adopt($parts);
		$this->release($this->parts);
		$this->parts = $parts;
		$this->structureChanged();
	}


	public function setCloseDelimiter(Token $closeDelimiter): void
	{
		$this->adopt($closeDelimiter);
		$this->release($this->closeDelimiter);
		$this->closeDelimiter = $closeDelimiter;
		$this->structureChanged();
	}
}
