<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Scalar;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Braced interpolation inside a string: {$expr} or ${name}.
 */
final class InterpolationNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openBrace,
		public ExpressionNode $expr,
		public Token $closeBrace,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openBrace, $this->expr, $this->closeBrace];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openBrace) {
			$this->setOpenBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('openBrace', $new));
		} elseif ($old === $this->expr) {
			$this->setExpr($new instanceof ExpressionNode ? $new : throw self::describeSlotMismatch('expr', $new));
		} elseif ($old === $this->closeBrace) {
			$this->setCloseBrace($new instanceof Token ? $new : throw self::describeSlotMismatch('closeBrace', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenBrace(Token $openBrace): void
	{
		$this->adopt($openBrace);
		$this->release($this->openBrace);
		$this->openBrace = $openBrace;
		$this->structureChanged();
	}


	public function setExpr(ExpressionNode $expr): void
	{
		$this->adopt($expr);
		$this->release($this->expr);
		$this->expr = $expr;
		$this->structureChanged();
	}


	public function setCloseBrace(Token $closeBrace): void
	{
		$this->adopt($closeBrace);
		$this->release($this->closeBrace);
		$this->closeBrace = $closeBrace;
		$this->structureChanged();
	}
}
