<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Scalar;

use PhpSyntax\Node;
use PhpSyntax\Token;


/**
 * Literal text between interpolations, whitespace included.
 */
final class InterpolatedStringPartNode extends Node
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $text,
	) {
	}


	public function getChildren(): array
	{
		return [$this->text];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->text) {
			$this->setText($new instanceof Token ? $new : throw self::describeSlotMismatch('text', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setText(Token $text): void
	{
		$this->adopt($text);
		$this->release($this->text);
		$this->text = $text;
		$this->structureChanged();
	}
}
