<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Scalar;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Nodes\NodeList;
use PhpSyntax\Token;


/**
 * Double-quoted string with interpolated variables or expressions.
 */
final class InterpolatedStringNode extends ExpressionNode
{
	/**
	 * @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $openQuote,
		public NodeList $parts,
		public Token $closeQuote,
	) {
	}


	public function getChildren(): array
	{
		return [$this->openQuote, $this->parts, $this->closeQuote];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->openQuote) {
			$this->setOpenQuote($new instanceof Token ? $new : throw self::describeSlotMismatch('openQuote', $new));
		} elseif ($old === $this->parts) {
			if (!$new instanceof NodeList) {
				throw self::describeSlotMismatch('parts', $new);
			}

			/** @var NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $new  the item type is erased at runtime */
			$this->setParts($new);
		} elseif ($old === $this->closeQuote) {
			$this->setCloseQuote($new instanceof Token ? $new : throw self::describeSlotMismatch('closeQuote', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setOpenQuote(Token $openQuote): void
	{
		$this->adopt($openQuote);
		$this->release($this->openQuote);
		$this->openQuote = $openQuote;
		$this->structureChanged();
	}


	/** @param NodeList<InterpolatedStringPartNode|InterpolationNode|ExpressionNode> $parts */
	public function setParts(NodeList $parts): void
	{
		$this->adopt($parts);
		$this->release($this->parts);
		$this->parts = $parts;
		$this->structureChanged();
	}


	public function setCloseQuote(Token $closeQuote): void
	{
		$this->adopt($closeQuote);
		$this->release($this->closeQuote);
		$this->closeQuote = $closeQuote;
		$this->structureChanged();
	}
}
