<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax\Nodes\Scalar;

use PhpSyntax\Node;
use PhpSyntax\Nodes\ExpressionNode;
use PhpSyntax\Token;


/**
 * Magic constant: __LINE__, __FILE__, __DIR__, __CLASS__, __TRAIT__, __METHOD__, __FUNCTION__, __PROPERTY__, __NAMESPACE__.
 */
final class MagicConstantNode extends ExpressionNode
{
	/**
	 * @internal nodes are created by the parser
	 */
	public function __construct(
		public Token $token,
	) {
	}


	public function getChildren(): array
	{
		return [$this->token];
	}


	public function replaceChild(Node|Token $old, Node|Token $new): void
	{
		if ($old === $this->token) {
			$this->setToken($new instanceof Token ? $new : throw self::describeSlotMismatch('token', $new));
		} else {
			throw self::describeChildMismatch($old);
		}
	}


	public function setToken(Token $token): void
	{
		$this->adopt($token);
		$this->release($this->token);
		$this->token = $token;
		$this->structureChanged();
	}
}
