<?php declare(strict_types=1);

namespace DressCode\Console;

use DressCode\Config\ResolvedConfig;
use DressCode\Config\ResolvedRule;
use DressCode\RuleInfo;
use function count, is_bool, is_string, strlen;


/**
 * Writes the standard of a project out of its resolved configuration: what every rule that runs asks for,
 * the options it asks it with, and the example chosen for it. It describes the part of a standard that is
 * enforced automatically; the review habits, the motivation and whatever no rule covers are not here.
 * @internal
 */
final class StandardPrinter
{
	public function __construct(
		private readonly ResolvedConfig $config,
		/** the directory the fixtures of the rules live in */
		private readonly string $fixtures,
	) {
	}


	public function print(string $title): string
	{
		$out = "# $title\n\n";
		$out .= "Generated by `dresscode standard`. It says what DressCode enforces, which is a part of a\n"
			. "coding standard, not the whole of it: what no rule covers is not here.\n\n";
		$out .= '- Composed of: ' . (implode(', ', array_map(fn(string $p) => "`$p`", $this->config->presets)) ?: 'no preset') . "\n";
		$out .= '- Indentation: ' . ($this->config->indent === "\t" ? 'a tab' : strlen($this->config->indent) . ' spaces') . "\n";
		$out .= '- Line ending: ' . match ($this->config->eol) {
			"\n" => 'LF',
			"\r\n" => 'CRLF',
			default => 'the one each file mostly has',
		} . "\n";
		$out .= '- Written for PHP ' . $this->config->phpVersion . "\n";

		$byCategory = [];
		foreach ($this->config->getActiveRules() as $rule) {
			$byCategory[self::categoryOf($rule)][] = $rule;
		}

		ksort($byCategory);
		$out .= "\n" . count($this->config->getActiveRules()) . " rules are enforced.\n";
		foreach ($byCategory as $category => $rules) {
			$out .= "\n## $category\n";
			foreach ($rules as $rule) {
				$out .= $this->printRule($rule);
			}
		}

		return $out;
	}


	private function printRule(ResolvedRule $rule): string
	{
		$info = RuleInfo::of($rule->class);
		$out = "\n### $rule->name\n\n";
		$out .= ($info->description === '' ? '' : "$info->description.\n\n");

		$options = [];
		foreach ($rule->getOrigins() as $path => $layers) {
			$options[] = "`$path`: " . self::format($layers[count($layers) - 1][1]);
		}

		// a rule that is one decision says its value even when nobody changed it: the value is the standard
		if (!$options && $info->decision !== null) {
			$options[] = "`$info->decision`: " . self::format($rule->options[$info->decision] ?? null);
		}

		if ($options) {
			$out .= 'As this project has it: ' . implode(', ', $options) . ".\n\n";
		}

		foreach (new ExplainPrinter($rule, $this->fixtures)->findExamples() as [$before, $after]) {
			$out .= "```php\n" . self::strip($before) . "```\n";
			if ($after !== null && $after !== $before) {
				$out .= "becomes\n\n```php\n" . self::strip($after) . "```\n";
			}
		}

		return $out;
	}


	/** The area a rule belongs to, that is the directory of its class, as the reference groups them too. */
	private static function categoryOf(ResolvedRule $rule): string
	{
		$parts = explode('\\', $rule->class);
		return $parts[count($parts) - 2];
	}


	private static function strip(string $code): string
	{
		$code = (string) preg_replace('~^<\?php\r?\n(?://[^\r\n]*\r?\n)*~', '', $code);
		return rtrim($code, "\r\n") . "\n";
	}


	private static function format(mixed $value): string
	{
		return match (true) {
			is_bool($value) => $value ? '`true`' : '`false`',
			$value === null => '`null`',
			is_string($value) => "`$value`",
			default => '`' . json_encode($value, JSON_UNESCAPED_SLASHES) . '`',
		};
	}
}
