#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * Generates the reference: rules.md from the registered rule classes and their option schemas, nodes.md from
 * grammar/nodes.php. Run by `composer reference`; the output is committed and CI diffs it.
 */

use DressCode\Config\RuleRegistry;
use DressCode\ConfigurableRule;
use DressCode\RuleInfo;
use Nette\Schema\Elements\AnyOf;
use Nette\Schema\Elements\Structure;
use Nette\Schema\Elements\Type;
use Nette\Schema\Kind;
use Nette\Schema\Processor;

require __DIR__ . '/../../vendor/autoload.php';


/** The type of an option as a word: int, ?string, one of a|b, list of int */
function describeType(Type|AnyOf|Structure|string $element): string
{
	if (is_string($element)) {
		return $element;
	}

	$description = $element->describe();
	$kind = $description['kind'] ?? null;
	$type = match ($kind) {
		Kind::Enum => implode(' \| ', array_map(fn($v) => is_string($v) ? "`$v`" : json_encode($v), $description['values'] ?? [])),
		Kind::Union => implode(' \| ', array_map(describeType(...), $description['variants'] ?? [])),
		Kind::List => 'list of ' . describeType($description['items'] ?? 'mixed'),
		Kind::Tuple => '[' . implode(', ', array_map(describeType(...), $description['items'] ?? $description['shape'] ?? [])) . ']',
		Kind::Structure => 'structure',
		default => $kind instanceof Kind ? strtolower($kind->name) : 'mixed',
	};
	return ($description['nullable'] ?? false) ? "?$type" : $type;
}


/** Text safe inside a table cell: a pipe would split it, a tag would be swallowed. */
function markdown(string $text): string
{
	return str_replace(['|', '<'], ['\|', '&lt;'], $text);
}


/** The category of a rule, that is the directory its class lies in. */
function category(string $class): string
{
	$parts = explode('\\', $class);
	return $parts[count($parts) - 2];
}


/** The kind of problem a rule is about, read off its name; the vocabulary puts it there. */
function kind(string $slug): string
{
	$suffixes = [
		'-spacing' => 'Spacing', '-blank-lines' => 'Blank lines', '-indentation' => 'Indentation',
		'-casing' => 'Casing', '-position' => 'Position', '-alignment' => 'Alignment',
		'-notation' => 'Notation', '-syntax' => 'Notation', '-operator' => 'Notation', '-required' => 'Required',
	];
	foreach ($suffixes as $suffix => $kind) {
		if (str_ends_with($slug, $suffix)) {
			return $kind;
		}
	}

	return match (true) {
		str_contains($slug, '-canonical-') => 'Notation',
		str_starts_with($slug, 'multi-line-') => 'Line breaks',
		str_starts_with($slug, 'useless-') => 'Redundancy',
		str_starts_with($slug, 'no-') => 'Forbidden',
		str_starts_with($slug, 'single-'), str_starts_with($slug, 'ordered-') => 'Shape',
		default => 'Other',
	};
}


/** A link to the entry of a rule: in a long list the slug alone reads better than the full name. */
function ruleLink(string $name): string
{
	return '[' . substr($name, strpos($name, '/') + 1) . '](#' . str_replace('/', '', $name) . ')';
}


$registry = new RuleRegistry;
$rules = $registry->getRules();
ksort($rules, SORT_STRING);

$byCategory = $byKind = [];
foreach ($rules as $name => $class) {
	$slug = substr($name, strpos($name, '/') + 1);
	$byCategory[category($class)][] = $name;
	$byKind[kind($slug)][] = $name;
}

ksort($byCategory);
ksort($byKind);

$out = "# Rules\n\nGenerated by `composer reference` from the rule classes; do not edit. "
	. count($rules) . " rules.\n\n";

$out .= "## By category\n\n";
foreach ($byCategory as $category => $names) {
	$out .= "**$category** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## By kind of problem\n\n";
foreach ($byKind as $kind => $names) {
	$out .= "**$kind** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## The rules\n\n";
foreach ($rules as $name => $class) {
	$info = RuleInfo::of($class);
	$out .= "### $name\n\n";
	$out .= ($info->description === '' ? '' : $info->description . ".\n\n");
	$facts = ["Stage: {$info->stage->name}"];
	if ($covers = $registry->getTranslator()->findForeignNames($name)) {
		$facts[] = 'Covers: ' . implode(', ', array_map(fn($a) => "`$a`", $covers));
	}

	if ($info->minPhpVersion !== null) {
		$facts[] = "Needs PHP $info->minPhpVersion";
	}

	if ($info->modifiesComments) {
		$facts[] = 'Modifies comments';
	}

	$out .= implode('. ', $facts) . ".\n\n";
	if (is_subclass_of($class, ConfigurableRule::class)) {
		$schema = $class::getOptionsSchema();
		if ($schema instanceof Structure) {
			$defaults = (array) (new Processor)->process($schema, []);
			$out .= "| Option | Type | Default | |\n|---|---|---|---|\n";
			foreach ($schema->getShape() as $option => $element) {
				if (!$element instanceof Type && !$element instanceof AnyOf && !$element instanceof Structure) {
					continue;
				}

				$description = $element->describe()['description'] ?? '';
				$out .= sprintf(
					"| `%s` | %s | `%s` | %s |\n",
					$option,
					describeType($element),
					markdown(json_encode($defaults[$option] ?? null, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)),
					markdown((string) $description),
				);
			}

			$out .= "\n";
		}
	}
}

file_put_contents(__DIR__ . '/rules.md', $out);
echo 'rules.md: ', count($rules), " rules\n";

/** @var array<string, array{description?: string, slots?: array<string, string>, implements?: list<string>, extends?: string, traits?: list<string>, manual?: bool}> $nodes */
$nodes = require __DIR__ . '/../../grammar/nodes.php';
$out = "# Nodes\n\nGenerated by `composer reference` from grammar/nodes.php; do not edit. "
	. count($nodes) . ' node classes under `PhpSyntax\Nodes`; a slot type is `Token`, a node class, `?` when optional, '
	. "`A|B` for a choice, `NodeList<T>` or `SeparatedNodeList<T>` for a list.\n\n";
foreach ($nodes as $class => $node) {
	$out .= "## $class\n\n";
	$out .= (($node['description'] ?? '') === '' ? '' : $node['description'] . "\n\n");
	$facts = [];
	if (isset($node['extends'])) {
		$facts[] = "Extends `{$node['extends']}`";
	}

	if (isset($node['implements'])) {
		$facts[] = 'Implements ' . implode(', ', array_map(fn($i) => "`$i`", $node['implements']));
	}

	if (isset($node['traits'])) {
		$facts[] = 'Uses ' . implode(', ', array_map(fn($t) => "`$t`", $node['traits']));
	}

	if (!empty($node['manual'])) {
		$facts[] = 'Handwritten class';
	}

	if ($facts) {
		$out .= implode('. ', $facts) . ".\n\n";
	}

	if (!empty($node['slots'])) {
		$out .= "| Slot | Type |\n|---|---|\n";
		foreach ($node['slots'] as $slot => $type) {
			$out .= sprintf("| `%s` | `%s` |\n", $slot, markdown($type));
		}

		$out .= "\n";
	}
}

file_put_contents(__DIR__ . '/nodes.md', $out);
echo 'nodes.md: ', count($nodes), " node classes\n";
