<?php declare(strict_types=1);


/**
 * Generates the reference: decisions.md from the decisions the rule classes declare, presets.md from the
 * registered presets. Run by `composer reference`; the output is committed and CI diffs it.
 */
use DressCode\{Config, DecisionKind, RuleInfo};
use DressCode\Config\{Catalogue, ConfigResolver, NeonReader, PluginRegistry};
use DressCode\Testing\RuleTester;

require __DIR__ . '/../../vendor/autoload.php';


/** Text safe inside a table cell: a pipe would split it, a tag outside a code span would be swallowed. */
function formatTableCell(string $text): string
{
	return (string) preg_replace_callback(
		'~(`+).*?\1|[^`]+|`+~s',
		fn(array $m) => str_replace(['|', '<'], ['\|', ($m[1] ?? '') === '' ? '&lt;' : '<'], $m[0]),
		$text,
	);
}


/**
 * The decisions under which a fixture lets its rule make a fix that changes what the code does, the proof that they have one.
 * @return array<string, true>
 */
function findRiskyDecisions(): array
{
	$decisions = [];
	foreach (require __DIR__ . '/../../tests/DressCode/Rules/rules.provider.php' as [$slug, $class]) {
		foreach ($class === null ? [] : (glob(__DIR__ . "/../../tests/DressCode/Rules/fixtures/$slug/*.code") ?: []) as $file) {
			$decisions += array_fill_keys(RuleTester::collectRiskyDecisions($class, $file), true);
		}
	}

	return $decisions;
}


/** A link to the entry of a decision: in a long list the path without its section reads better. */
function formatDecisionLink(string $path): string
{
	return '[' . substr($path, strpos($path, '.') + 1) . '](#' . strtolower(str_replace('.', '', $path)) . ')';
}


/** A value as the reference writes it: a word for its map of `*` and for a tolerance of that word alone. */
function formatValue(DressCode\Value $value): string
{
	$data = $value->toData();
	$data = $value->domain instanceof DressCode\Domains\Words && is_array($data) && array_keys($data) === ['*'] ? $data['*'] : $data;
	$data = $value->domain instanceof DressCode\Domains\Words && is_array($data) && count($data) === 1 ? $data[0] : $data;
	return '`' . (is_string($data) ? $data : json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) . '`';
}


$registry = new PluginRegistry;
$resolver = new ConfigResolver($registry);
$catalogue = $resolver->getCatalogue();
$riskyDecisions = findRiskyDecisions();
$standards = [];
foreach (['perCs', 'psr12', 'nette', 'symfony'] as $standard) {
	$standards[$standard] = $resolver->resolve(new Config(use: ["dresscode/$standard"]), Config::DefaultPhpVersion)->decisions;
}

// the sections of the core in their order
$bySection = array_fill_keys(Catalogue::CoreSections, []);
$byVersion = $phpNeeds = [];
foreach ($catalogue->getDecisions() as $path => $decision) {
	$bySection[explode('.', $path)[0]][$path] = $decision;
	// a decision takes effect where the least demanding of its rules runs
	$rules = $catalogue->getRulesOf($path);
	usort($rules, fn(string $a, string $b): int => version_compare(RuleInfo::of($a)->getMinPhpVersion() ?? '0', RuleInfo::of($b)->getMinPhpVersion() ?? '0'));
	$info = RuleInfo::of($rules[0]);
	$minPhpVersion = $info->getMinPhpVersion();
	if ($minPhpVersion !== null && version_compare($minPhpVersion, Config::MinPhpVersion, '>')) {
		$byVersion[$minPhpVersion][] = $path;
		$phpNeeds[$path] = $info->requires['php'];
	}
}

$bySection = array_filter($bySection);
uksort($byVersion, fn(string $a, string $b): int => version_compare($a, $b));

$out = "# Decisions\n\nGenerated by `composer reference` from the catalogue; do not edit. "
	. count($catalogue->getDecisions()) . ' decisions in ' . count($bySection) . " sections.\n\n";

$out .= "## By section\n\n";
foreach ($bySection as $section => $decisions) {
	$out .= "**$section** (" . count($decisions) . '): ' . implode(', ', array_map(formatDecisionLink(...), array_keys($decisions))) . "\n\n";
}

$out .= "## By the version of PHP a decision needs\n\n";
$out .= 'A decision about a construct older than PHP ' . Config::MinPhpVersion . ", which every target has, is in none of these.\n\n";
foreach ($byVersion as $version => $paths) {
	$out .= "**PHP $version** (" . count($paths) . '): ' . implode(', ', array_map(formatDecisionLink(...), $paths)) . "\n\n";
}

foreach ($bySection as $section => $decisions) {
	$out .= "## $section\n\n";
	foreach ($decisions as $path => $decision) {
		$rules = $catalogue->getRulesOf($path);
		$out .= "### $path\n\n" . formatTableCell($decision->description) . ".\n\n";
		foreach ($decision->notes as $note) {
			$out .= formatTableCell($note) . "\n\n";
		}

		$facts = [match ($decision->kind) {
			DecisionKind::Parameter => 'A parameter, which refines a requirement and turns nothing on; ' . ($decision->default === null ? 'no default' : 'by default ' . formatValue($decision->getDefault())),
			DecisionKind::Fact => 'A fact of the project, which its rule guards',
			DecisionKind::Requirement => 'A requirement',
		}];
		$facts[] = 'Takes: ' . $decision->describeValues();
		$facts[] = 'The standards: ' . implode(', ', array_map(
			fn(string $standard) => "$standard " . formatValue($standards[$standard][$path]->value),
			array_keys($standards),
		));
		// the decision needs what every one of its rules needs
		$needs = null;
		$modifiesComments = false;
		foreach ($rules as $rule) {
			$info = RuleInfo::of($rule);
			$facts[] = 'Rule `' . $rule . '`, stage ' . $info->stage->name;
			$ruleNeeds = [];
			foreach ($info->getRequiredPackages() as $package => $constraint) {
				$ruleNeeds[] = "Needs `$package`" . ($constraint === '*' ? '' : " $constraint");
			}

			if ($info->typesRequired) {
				$ruleNeeds[] = 'Needs the types of the code, so it takes effect only with `typeAnalysis: phpstan`';
			}

			$needs = $needs === null ? $ruleNeeds : array_values(array_intersect($needs, $ruleNeeds));
			$modifiesComments = $modifiesComments || $info->modifiesComments;
		}

		foreach ($catalogue->getReadersOf($path) as $rule) {
			$facts[] = 'Read by rule `' . $rule . '`, which this decision does not turn on';
		}

		if ($covers = $registry->translator->findForeignNames([$path])) {
			$facts[] = 'Covers: ' . implode(', ', array_map(fn($a) => "`$a`", $covers));
		}

		if (isset($phpNeeds[$path])) {
			$facts[] = "Needs PHP $phpNeeds[$path]";
		}

		array_push($facts, ...$needs ?? []);
		if ($modifiesComments) {
			$facts[] = 'Modifies comments';
		}

		if (isset($riskyDecisions[$path])) {
			$facts[] = 'May have risky fixes, made once the decision is named in `fixRisky` or with `--fix-risky`';
		}

		$out .= implode("\n", array_map(fn(string $fact) => '- ' . formatTableCell($fact), $facts)) . "\n\n";
	}
}

file_put_contents(__DIR__ . '/decisions.md', rtrim($out) . "\n");
echo 'decisions.md: ', count($catalogue->getDecisions()), " decisions\n";


// presets.md: what each preset is and what it builds on
$presets = $registry->presets;
$out = "# Presets\n\nGenerated by `composer reference` from the preset files; do not edit. "
	. count($presets) . " presets.\n\n"
	. "A project takes one of the standards (`dresscode/perCs`, `dresscode/psr12`, `dresscode/nette`, `dresscode/symfony`)\n"
	. "as its base, and the description of every other preset says what it adds to it.\n\n"
	. "| Preset | Builds on | |\n|---|---|---|\n";
foreach ($presets as $name => $file) {
	$parents = array_map(
		fn(string $entry) => '`' . $registry->resolvePreset($entry) . '`',
		NeonReader::readPreset($file, $name)->use,
	);
	$out .= sprintf(
		"| `%s` | %s | %s |\n",
		$name,
		$parents === [] ? '' : implode(', ', $parents),
		formatTableCell(NeonReader::readPresetTitle($file)),
	);
}

file_put_contents(__DIR__ . '/presets.md', $out);
echo 'presets.md: ', count($presets), " presets\n";
