#!/usr/bin/env php
<?php declare(strict_types=1);


/**
 * Generates the reference: rules.md from the registered rule classes and their option schemas, presets.md
 * from the registered presets. Run by `composer reference`; the output is committed and CI diffs it.
 */
use DressCode\{Config, ConfigurableRule, PresetInfo, RuleInfo};
use DressCode\Config\RuleRegistry;
use Nette\Schema\Elements\{AnyOf, Structure, Type};
use Nette\Schema\{Kind, Processor};

require __DIR__ . '/../../vendor/autoload.php';


/** The type of an option as a word: int, ?string, one of a|b, list of int */
function describeType(Type|AnyOf|Structure|string $element): string
{
	if (is_string($element)) {
		return $element;
	}

	$description = $element->describe();
	$kind = $description['kind'] ?? null;
	$type = match ($kind) {
		Kind::Enum => implode(' \| ', array_map(fn($v) => is_string($v) ? "`$v`" : json_encode($v), $description['values'] ?? [])),
		Kind::Union => implode(' \| ', [
			...array_map(fn($v) => is_string($v) ? "`$v`" : json_encode($v), $description['values'] ?? []),
			...array_map(describeType(...), $description['variants'] ?? []),
		]),
		Kind::List => 'list of ' . (str_contains($item = describeType($description['items'] ?? 'mixed'), ' \| ') ? "($item)" : $item),
		Kind::Tuple => '[' . implode(', ', array_map(describeType(...), $description['items'] ?? $description['shape'] ?? [])) . ']',
		Kind::Structure => 'structure',
		default => $kind instanceof Kind ? strtolower($kind->name) : 'mixed',
	};
	return ($description['nullable'] ?? false) ? "?$type" : $type;
}


/** Text safe inside a table cell: a pipe would split it, a tag would be swallowed. */
function markdown(string $text): string
{
	return str_replace(['|', '<'], ['\|', '&lt;'], $text);
}


/** The category of a rule, that is the directory its class lies in. */
function category(string $class): string
{
	$parts = explode('\\', $class);
	return $parts[count($parts) - 2];
}


/** The kind of problem a rule is about, read off its name; the vocabulary puts it there. */
function kind(string $slug): string
{
	$suffixes = [
		'-spacing' => 'Spacing', '-blank-lines' => 'Blank lines', '-indentation' => 'Indentation',
		'-casing' => 'Casing', '-position' => 'Position', '-alignment' => 'Alignment',
		'-notation' => 'Notation', '-syntax' => 'Notation', '-operator' => 'Notation', '-required' => 'Required',
	];
	foreach ($suffixes as $suffix => $kind) {
		if (str_ends_with($slug, $suffix)) {
			return $kind;
		}
	}

	return match (true) {
		str_contains($slug, '-canonical-') => 'Notation',
		str_contains($slug, '-for-') => 'Replacement',
		str_starts_with($slug, 'multi-line-') => 'Line breaks',
		str_starts_with($slug, 'useless-') => 'Redundancy',
		str_starts_with($slug, 'no-') => 'Forbidden',
		str_starts_with($slug, 'single-'), str_starts_with($slug, 'ordered-') => 'Shape',
		default => 'Other',
	};
}


/** A fixture that lets the rule make a fix which changes what the code does is the proof that it has one. */
function hasRiskyFixture(string $name): bool
{
	$slug = substr($name, strpos($name, '/') + 1);
	foreach (glob(__DIR__ . "/../../tests/DressCode/Rules/fixtures/$slug/*.code") ?: [] as $file) {
		// the header as RuleTester reads it: the lines up to the first one that is not blank, a comment or the open tag
		foreach (preg_split('~\r?\n~', (string) file_get_contents($file)) ?: [] as $line) {
			if (preg_match('~^//\s*risky\s*$~i', $line)) {
				return true;
			} elseif (!preg_match('~^(\s*|//.*|#!.*|.*<\?php\b.*)$~i', $line)) {
				break;
			}
		}
	}

	return false;
}


/** A link to the entry of a rule: in a long list the slug alone reads better than the full name. */
function ruleLink(string $name): string
{
	return '[' . substr($name, strpos($name, '/') + 1) . '](#' . str_replace('/', '', $name) . ')';
}


$registry = new RuleRegistry;
$rules = $registry->getRules();
ksort($rules, SORT_STRING);

$byCategory = $byKind = $byVersion = $byGroup = [];
foreach ($rules as $name => $class) {
	$slug = substr($name, strpos($name, '/') + 1);
	$info = RuleInfo::of($class);
	$byCategory[category($class)][] = $name;
	$byKind[kind($slug)][] = $name;
	$byGroup[$info->group === null ? 'no group, so a standard chooses it or the project names it' : $info->group->value][] = $name;
	$minPhpVersion = $info->getMinPhpVersion();
	if ($minPhpVersion !== null && version_compare($minPhpVersion, Config::MinPhpVersion, '>')) {
		$byVersion[$minPhpVersion][] = $name;
	}
}

ksort($byCategory);
ksort($byKind);
uksort($byVersion, fn(string $a, string $b): int => version_compare($a, $b));

$out = "# Rules\n\nGenerated by `composer reference` from the rule classes; do not edit. "
	. count($rules) . " rules.\n\n";

$out .= "## By category\n\n";
foreach ($byCategory as $category => $names) {
	$out .= "**$category** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## By kind of problem\n\n";
foreach ($byKind as $kind => $names) {
	$out .= "**$kind** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## By group\n\n";
$out .= "A project asks for a group by name (`groups: [cleanup]`) and gets every rule of it with the options it defaults to.\n\n";
foreach ($byGroup as $group => $names) {
	$out .= "**$group** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## By the version of PHP a rule needs\n\n";
$out .= 'A rule writing a construct older than PHP ' . Config::MinPhpVersion . ", which every target has, is in none of these.\n\n";
foreach ($byVersion as $version => $names) {
	$out .= "**PHP $version** (" . count($names) . '): ' . implode(', ', array_map(ruleLink(...), $names)) . "\n\n";
}

$out .= "## The rules\n\n";
foreach ($rules as $name => $class) {
	$info = RuleInfo::of($class);
	$out .= "### $name\n\n";
	$out .= ($info->description === '' ? '' : $info->description . ".\n\n");
	$facts = ["Stage: {$info->stage->name}"];

	$minPhpVersion = $info->getMinPhpVersion();
	if ($minPhpVersion !== null && version_compare($minPhpVersion, Config::MinPhpVersion, '>')) {
		$facts[] = "Needs PHP $minPhpVersion";
	}

	foreach ($info->getRequiredPackages() as $package => $version) {
		$facts[] = "Needs `$package`" . ($version === null ? '' : " $version");
	}

	if ($info->requiresTypes) {
		$facts[] = 'Needs the types of the code, so it runs only with `types: phpstan`';
	}

	if ($info->modifiesComments) {
		$facts[] = 'Modifies comments';
	}

	if ($info->risky) {
		$facts[] = 'Every fix may change what the code does, so it is made once the rule is named in `fixRisky` or with `--fix-risky`';
	} elseif (hasRiskyFixture($name)) {
		$facts[] = 'May have risky fixes, made once the rule is named in `fixRisky` or with `--fix-risky`';
	}

	if ($info->decision !== null) {
		$facts[] = "One decision, so a value written for the rule fills `$info->decision`";
	}

	$out .= implode('. ', $facts) . ".\n\n";
	if (is_subclass_of($class, ConfigurableRule::class)) {
		$schema = $class::getOptionsSchema();
		if ($schema instanceof Structure) {
			$defaults = (array) (new Processor)->process($schema, []);
			$out .= "| Option | Type | Default | |\n|---|---|---|---|\n";
			foreach ($schema->getShape() as $option => $element) {
				if (!$element instanceof Type && !$element instanceof AnyOf && !$element instanceof Structure) {
					continue;
				}

				$description = $element->describe()['description'] ?? '';
				$out .= sprintf(
					"| `%s` | %s | `%s` | %s |\n",
					$option,
					describeType($element),
					markdown(json_encode($defaults[$option] ?? null, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)),
					markdown((string) $description),
				);
			}

			$out .= "\n";

		} elseif (
			($schema instanceof Type || $schema instanceof AnyOf)
			&& ($description = $schema->describe()['description'] ?? null) !== null
		) {
			// a rule whose options are one map has no shape to tabulate, so its description says what goes in it
			$out .= 'Options: ' . markdown((string) $description) . ".\n\n";
		}
	}
}

file_put_contents(__DIR__ . '/rules.md', $out);
echo 'rules.md: ', count($rules), " rules\n";


// presets.md: what each preset is, what it builds on and how many rules it has a say about
$presets = $registry->getPresets();
$out = "# Presets\n\nGenerated by `composer reference` from the preset classes; do not edit. "
	. count($presets) . " presets.\n\n"
	. "A project takes one of the standards (`dresscode/per`, `dresscode/psr12`, `dresscode/nette`, `dresscode/symfony`)\n"
	. "as its base, and the description of every other preset says what it adds to it.\n\n"
	. "| Preset | Builds on | Rules | |\n|---|---|---|---|\n";
foreach ($presets as $name => $class) {
	$info = PresetInfo::of($class);
	$profile = (new $class)->getProfile();
	$parents = array_map(fn(string $parent) => '`' . PresetInfo::of($registry->resolvePreset($parent))->name . '`', $profile->presets);
	$out .= sprintf(
		"| `%s` | %s | %d | %s |\n",
		$name,
		$parents === [] ? '' : implode(', ', $parents),
		count($profile->rules),
		markdown($info->description),
	);
}

file_put_contents(__DIR__ . '/presets.md', $out);
echo 'presets.md: ', count($presets), " presets\n";
